using System;
using System.Collections.Generic;

namespace Nin.Geolocation.Utils
{
    public static class NavneTyper
    {
        private static Dictionary<string, int> _navneTypeDictonary;

        private static Dictionary<string, int> NavneTypeDictonary
        {
            get
            {
                if (_navneTypeDictonary != null) return _navneTypeDictonary;

                _navneTypeDictonary = new Dictionary<string, int>(StringComparer.InvariantCultureIgnoreCase)
                {
                    {"Berg", 2},
                    {"Fjell", 3},
                    {"Fjellside", 2},
                    {"Fjellområde", 3},
                    {"Skogområde", 2},
                    {"Landskapsområde", 2},
                    {"Hei", 2},
                    {"Høyde", 2},
                    {"Ås", 2},
                    {"Rygg", 2},
                    {"Haug", 2},
                    {"Topp (fjelltopp/tind)", 2},
                    {"Hylle (hjell)", 2},
                    {"Fjellkant (aksel)", 2},
                    {"Bakke", 2},
                    {"Li", 2},
                    {"Stup", 2},
                    {"Vidde", 2},
                    {"Slette", 2},
                    {"Mo", 2},
                    {"Dalføre", 3},
                    {"Dal", 3},
                    {"Botn", 2},
                    {"Senkning", 2},
                    {"Skar", 2},
                    {"Juv", 2},
                    {"Søkk", 2},
                    {"Stein", 2},
                    {"Grotte", 2},
                    {"Heller", 2},
                    {"Terrengdetalj", 2},
                    {"Innsjø", 2},
                    {"Gruppe av vann", 3},
                    {"Vann", 2},
                    {"Gruppe av tjern", 2},
                    {"Tjern", 2},
                    {"Pytt", 2},
                    {"Sund", 2},
                    {"Vik", 2},
                    {"Elv", 2},
                    {"Bekk", 2},
                    {"Grøft", 2},
                    {"Foss", 2},
                    {"Stryk", 2},
                    {"Os", 2},
                    {"Høl", 2},
                    {"Lone", 2},
                    {"Kilde", 2},
                    {"Øy", 2},
                    {"Øygruppe", 3},
                    {"Holme", 2},
                    {"Halvøy", 3},
                    {"Nes", 2},
                    {"Nes ved elver", 2},
                    {"Eid", 2},
                    {"Strand", 2},
                    {"Isbre", 2},
                    {"Fonn", 2},
                    {"Skjær", 2},
                    {"Båe", 2},
                    {"Grunne", 2},
                    {"Banke", 2},
                    {"Vanndetalj", 2},
                    {"Elvemel", 2},
                    {"Skog", 2},
                    {"Myr", 2},
                    {"Utmark", 2},
                    {"Sva", 2},
                    {"Ur", 2},
                    {"Skred", 2},
                    {"Øyr", 2},
                    {"Sand", 2},
                    {"Eng", 2},
                    {"Jorde", 2},
                    {"Havnehage", 2},
                    {"Torvtak", 2},
                    {"Setervoll", 2},
                    {"Park", 2},
                    {"Grustak/Steinbrudd", 2},
                    {"Tømmervelte", 2},
                    {"Fjord", 3},
                    {"Fjordmunning", 2},
                    {"Havområde", 3},
                    {"Sjøstykke", 2},
                    {"Sund i sjø", 2},
                    {"Vik i sjø", 2},
                    {"Våg", 2},
                    {"Øy i sjø", 2},
                    {"Øygruppe i sjø", 3},
                    {"Holme i sjø", 2},
                    {"Holmegruppe i sjø", 2},
                    {"Halvøy i sjø", 2},
                    {"Nes i sjø", 2},
                    {"Eid i sjø", 2},
                    {"Strand i sjø", 2},
                    {"Skjær i sjø", 2},
                    {"Båe i sjø", 2},
                    {"Grunne i sjø", 2},
                    {"Renne", 2},
                    {"Banke i sjø", 2},
                    {"Bakke i sjø", 2},
                    {"Søkk i sjø", 2},
                    {"Dyp (havdyp)", 3},
                    {"Rygg i sjø", 3},
                    {"Egg", 2},
                    {"Klakk", 2},
                    {"Fiskeplass", 2},
                    {"By", 3},
                    {"Bydel", 2},
                    {"Tettsted", 2},
                    {"Tettsteddel", 2},
                    {"Tettbebyggelse", 2},
                    {"Bygdelag (bygd)", 2},
                    {"Grend", 2},
                    {"Boligfelt", 2},
                    {"Hyttefelt", 2},
                    {"Borettslag", 1},
                    {"Industriområde", 2},
                    {"Bruk (gardsbruk)", 2},
                    {"Enebolig/mindre boligbygg (villa)", 1},
                    {"Fritidsbolig (hytte, sommerhus)", 1},
                    {"Seter (sel, støl)", 1},
                    {"Bygg for jordbruk, fiske og fangst", 1},
                    {"Fabrikk", 1},
                    {"Kraftstasjon", 2},
                    {"Bergverk (underjord./dagbrudd)", 2},
                    {"Verksted", 1},
                    {"Forretningsbygg", 2},
                    {"Hotell", 1},
                    {"Pensjonat", 1},
                    {"Turisthytte", 1},
                    {"Serveringssted", 1},
                    {"Campingplass", 1},
                    {"Skole", 1},
                    {"Universitet/høgskole", 1},
                    {"Sykehus", 1},
                    {"Helseinstitusjon", 1},
                    {"Kirke", 1},
                    {"Annen bygning for religiøse aktiviteter.", 1},
                    {"Forsamlingshus/Kulturhus", 1},
                    {"Vaktstasjon/Beredsskapsbygning", 1},
                    {"Militært bygg/Anlegg", 1},
                    {"Idrettshall", 1},
                    {"Fyr(Fyrstasjon)", 1},
                    {"Lykt (Fyrlykt)", 1},
                    {"TV/Radio-mast", 1},
                    {"Barnehage", 1},
                    {"Poststed (Postkontor)", 1},
                    {"Adressenavn", 2},
                    {"Rådhus (komm, fylke, stat)", 2},
                    {"Fengsel", 1},
                    {"Museum/ Galleri/Bibliotek", 2},
                    {"Garasje/hangarbygg", 1},
                    {"Veg (Gate)", 2},
                    {"Traktorveg", 2},
                    {"Sti", 2},
                    {"Farled/Skipslei", 2},
                    {"Ferjestrekning", 2},
                    {"Jernbanestrekning", 2},
                    {"Vegstrekning", 2},
                    {"Bru", 1},
                    {"Klopp", 2},
                    {"Vad", 2},
                    {"Tunnel", 2},
                    {"Kryss (Veg/Gate)", 2},
                    {"Vegbom", 2},
                    {"Bomstasjon", 1},
                    {"Grind", 2},
                    {"Parkeringsplass", 1},
                    {"Kai", 2},
                    {"Brygge", 1},
                    {"Ferjelem", 2},
                    {"Utstikker", 2},
                    {"Molo", 2},
                    {"Sluse", 2},
                    {"Kanal", 2},
                    {"Ankringsplass", 2},
                    {"Havn", 2},
                    {"Stasjon", 2},
                    {"Holdeplass", 2},
                    {"Busstopp", 1},
                    {"Flyplass", 2},
                    {"Landingsstripe", 2},
                    {"Plass/torg", 2},
                    {"Eiendommer", 2},
                    {"Nasjon", 5},
                    {"Fylke", 4},
                    {"Kommune", 3},
                    {"Adm. by", 2},
                    {"Adm. bydel", 2},
                    {"Adm. tettsted", 2},
                    {"Sogn", 3},
                    {"Grunnkrets", 2},
                    {"Allmenning", 2},
                    {"Skytefelt", 2},
                    {"Verneområder", 2},
                    {"Soneinndeling til havs", 2},
                    {"Annen adm. Inndeling", 2},
                    {"Grensemerke", 1},
                    {"Idrettsanlegg", 2},
                    {"Skytebane", 2},
                    {"Gravplass", 2},
                    {"Skiheis", 2},
                    {"Fjellheis", 2},
                    {"Slalåm- og utforbakke", 2},
                    {"Småbåthavn", 2},
                    {"Badeplass", 2},
                    {"Fornøyelsespark", 2},
                    {"Rørledning", 2},
                    {"Oljeinstallasjon (Sjø)", 2},
                    {"Kraftledning", 2},
                    {"Kraftgate (Rørgate)", 2},
                    {"Kabel", 2},
                    {"Dam", 2},
                    {"Tømmerrenne", 2},
                    {"Taubane", 2},
                    {"Fløtningsannlegg", 2},
                    {"Fiskeoppdrettsanlegg", 2},
                    {"Gammel bosettingsplass", 2},
                    {"Offersted", 1},
                    {"Severdighet", 2},
                    {"Utsiktspunkt", 1},
                    {"Melkeplass", 2},
                    {"Annen kulturdetalj", 2},
                    {"Gjerde", 2},
                    {"Stø", 2},
                    {"Varde", 2},
                    {"Lanterne", 1},
                    {"Stang", 2},
                    {"Stake", 1},
                    {"Lysbøye", 1},
                    {"Båke", 2},
                    {"Overett", 2},
                    {"Rasteplass", 1},
                    {"Del av innsjø", 2},
                    {"Boligblokk", 2},
                    {"Fyllplass", 2},
                    {"Gard", 1},
                    {"Golfbane", 2},
                    {"Kystradiostasjon", 2},
                           
                };

                return _navneTypeDictonary;
            }
        }

        public static int GetLevelForType(string typeName)
        {
            if (!NavneTypeDictonary.ContainsKey(typeName)) return 2;
            return NavneTypeDictonary[typeName];
        }
    }
}