//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(Namespace="https://ws.geonorge.no/SKWS2/services/Eiendom", ConfigurationName="Eiendom")]
public interface Eiendom
{
    
    // CODEGEN: Generating message contract since the wrapper namespace (http://ws.ngisedmws.sk.hosledata.no) of message edmSokRequest does not match the default value (https://ws.geonorge.no/SKWS2/services/Eiendom)
    [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
    [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, Use=System.ServiceModel.OperationFormatUse.Encoded)]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(EdmKoordRec))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(EdmRecord))]
    edmSokResponse edmSok(edmSokRequest request);
    
    [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
    System.Threading.Tasks.Task<edmSokResponse> edmSokAsync(edmSokRequest request);
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:edm2.ws.statkart.no")]
public partial class EdmSokRes
{
    
    private EdmRecord[] edmRecordsField;
    
    private EdmSokStatus sokStatusField;
    
    /// <remarks/>
    [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
    public EdmRecord[] edmRecords
    {
        get
        {
            return this.edmRecordsField;
        }
        set
        {
            this.edmRecordsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
    public EdmSokStatus sokStatus
    {
        get
        {
            return this.sokStatusField;
        }
        set
        {
            this.sokStatusField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:edm2.ws.statkart.no")]
public partial class EdmRecord
{
    
    private double arealField;
    
    private string brukAvGrunnField;
    
    private string bruksNavnField;
    
    private int bruksNummerField;
    
    private string eiendomsTypeField;
    
    private int festeNummerField;
    
    private int gaardsNummerField;
    
    private int kommuneNummerField;
    
    private EdmKoordRec[] koordsField;
    
    private string oppdaterDatoField;
    
    private int seksjonsNummerField;
    
    private bool tinglystField;
    
    /// <remarks/>
    public double areal
    {
        get
        {
            return this.arealField;
        }
        set
        {
            this.arealField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
    public string brukAvGrunn
    {
        get
        {
            return this.brukAvGrunnField;
        }
        set
        {
            this.brukAvGrunnField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
    public string bruksNavn
    {
        get
        {
            return this.bruksNavnField;
        }
        set
        {
            this.bruksNavnField = value;
        }
    }
    
    /// <remarks/>
    public int bruksNummer
    {
        get
        {
            return this.bruksNummerField;
        }
        set
        {
            this.bruksNummerField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
    public string eiendomsType
    {
        get
        {
            return this.eiendomsTypeField;
        }
        set
        {
            this.eiendomsTypeField = value;
        }
    }
    
    /// <remarks/>
    public int festeNummer
    {
        get
        {
            return this.festeNummerField;
        }
        set
        {
            this.festeNummerField = value;
        }
    }
    
    /// <remarks/>
    public int gaardsNummer
    {
        get
        {
            return this.gaardsNummerField;
        }
        set
        {
            this.gaardsNummerField = value;
        }
    }
    
    /// <remarks/>
    public int kommuneNummer
    {
        get
        {
            return this.kommuneNummerField;
        }
        set
        {
            this.kommuneNummerField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
    public EdmKoordRec[] koords
    {
        get
        {
            return this.koordsField;
        }
        set
        {
            this.koordsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
    public string oppdaterDato
    {
        get
        {
            return this.oppdaterDatoField;
        }
        set
        {
            this.oppdaterDatoField = value;
        }
    }
    
    /// <remarks/>
    public int seksjonsNummer
    {
        get
        {
            return this.seksjonsNummerField;
        }
        set
        {
            this.seksjonsNummerField = value;
        }
    }
    
    /// <remarks/>
    public bool tinglyst
    {
        get
        {
            return this.tinglystField;
        }
        set
        {
            this.tinglystField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:edm2.ws.statkart.no")]
public partial class EdmKoordRec
{
    
    private double austField;
    
    private double hoydeField;
    
    private int koordSystField;
    
    private double nordField;
    
    /// <remarks/>
    public double aust
    {
        get
        {
            return this.austField;
        }
        set
        {
            this.austField = value;
        }
    }
    
    /// <remarks/>
    public double hoyde
    {
        get
        {
            return this.hoydeField;
        }
        set
        {
            this.hoydeField = value;
        }
    }
    
    /// <remarks/>
    public int koordSyst
    {
        get
        {
            return this.koordSystField;
        }
        set
        {
            this.koordSystField = value;
        }
    }
    
    /// <remarks/>
    public double nord
    {
        get
        {
            return this.nordField;
        }
        set
        {
            this.nordField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:edm2.ws.statkart.no")]
public partial class EdmSokStatus
{
    
    private string meldingField;
    
    private bool mereDataField;
    
    private bool okField;
    
    /// <remarks/>
    [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
    public string melding
    {
        get
        {
            return this.meldingField;
        }
        set
        {
            this.meldingField = value;
        }
    }
    
    /// <remarks/>
    public bool mereData
    {
        get
        {
            return this.mereDataField;
        }
        set
        {
            this.mereDataField = value;
        }
    }
    
    /// <remarks/>
    public bool ok
    {
        get
        {
            return this.okField;
        }
        set
        {
            this.okField = value;
        }
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(WrapperName="edmSok", WrapperNamespace="http://ws.ngisedmws.sk.hosledata.no", IsWrapped=true)]
public partial class edmSokRequest
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
    public string brukerid;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
    public string passord;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
    public string aliasId;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=3)]
    public int kommuneNummer;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=4)]
    public int gaardsNummer;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=5)]
    public int bruksNummer;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=6)]
    public int festeNummer;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=7)]
    public int seksjonsNummer;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=8)]
    public int maxAnt;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=9)]
    public int tilSosiKoordSyst;
    
    public edmSokRequest()
    {
    }
    
    public edmSokRequest(string brukerid, string passord, string aliasId, int kommuneNummer, int gaardsNummer, int bruksNummer, int festeNummer, int seksjonsNummer, int maxAnt, int tilSosiKoordSyst)
    {
        this.brukerid = brukerid;
        this.passord = passord;
        this.aliasId = aliasId;
        this.kommuneNummer = kommuneNummer;
        this.gaardsNummer = gaardsNummer;
        this.bruksNummer = bruksNummer;
        this.festeNummer = festeNummer;
        this.seksjonsNummer = seksjonsNummer;
        this.maxAnt = maxAnt;
        this.tilSosiKoordSyst = tilSosiKoordSyst;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(WrapperName="edmSokResponse", WrapperNamespace="https://ws.geonorge.no/SKWS2/services/Eiendom", IsWrapped=true)]
public partial class edmSokResponse
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
    public EdmSokRes edmSokReturn;
    
    public edmSokResponse()
    {
    }
    
    public edmSokResponse(EdmSokRes edmSokReturn)
    {
        this.edmSokReturn = edmSokReturn;
    }
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface EiendomChannel : Eiendom, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class EiendomClient : System.ServiceModel.ClientBase<Eiendom>, Eiendom
{
    
    public EiendomClient()
    {
    }
    
    public EiendomClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public EiendomClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public EiendomClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public EiendomClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    edmSokResponse Eiendom.edmSok(edmSokRequest request)
    {
        return base.Channel.edmSok(request);
    }
    
    public EdmSokRes edmSok(string brukerid, string passord, string aliasId, int kommuneNummer, int gaardsNummer, int bruksNummer, int festeNummer, int seksjonsNummer, int maxAnt, int tilSosiKoordSyst)
    {
        edmSokRequest inValue = new edmSokRequest();
        inValue.brukerid = brukerid;
        inValue.passord = passord;
        inValue.aliasId = aliasId;
        inValue.kommuneNummer = kommuneNummer;
        inValue.gaardsNummer = gaardsNummer;
        inValue.bruksNummer = bruksNummer;
        inValue.festeNummer = festeNummer;
        inValue.seksjonsNummer = seksjonsNummer;
        inValue.maxAnt = maxAnt;
        inValue.tilSosiKoordSyst = tilSosiKoordSyst;
        edmSokResponse retVal = ((Eiendom)(this)).edmSok(inValue);
        return retVal.edmSokReturn;
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    System.Threading.Tasks.Task<edmSokResponse> Eiendom.edmSokAsync(edmSokRequest request)
    {
        return base.Channel.edmSokAsync(request);
    }
    
    public System.Threading.Tasks.Task<edmSokResponse> edmSokAsync(string brukerid, string passord, string aliasId, int kommuneNummer, int gaardsNummer, int bruksNummer, int festeNummer, int seksjonsNummer, int maxAnt, int tilSosiKoordSyst)
    {
        edmSokRequest inValue = new edmSokRequest();
        inValue.brukerid = brukerid;
        inValue.passord = passord;
        inValue.aliasId = aliasId;
        inValue.kommuneNummer = kommuneNummer;
        inValue.gaardsNummer = gaardsNummer;
        inValue.bruksNummer = bruksNummer;
        inValue.festeNummer = festeNummer;
        inValue.seksjonsNummer = seksjonsNummer;
        inValue.maxAnt = maxAnt;
        inValue.tilSosiKoordSyst = tilSosiKoordSyst;
        return ((Eiendom)(this)).edmSokAsync(inValue);
    }
}
