//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(Namespace="https://ws.geonorge.no/SKWS2/services/Adresse", ConfigurationName="Adresse")]
public interface Adresse
{
    
    // CODEGEN: Generating message contract since the wrapper namespace (http://ws.ngisadrws.sk.hosledata.no) of message adresseSokRequest does not match the default value (https://ws.geonorge.no/SKWS2/services/Adresse)
    [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
    [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, Use=System.ServiceModel.OperationFormatUse.Encoded)]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(FylkeKomRec))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(FylkeRec))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(KommuneRecord))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(GateRecord))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(AdresseRecord2))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(AdresseRecord))]
    adresseSokResponse adresseSok(adresseSokRequest request);
    
    [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
    System.Threading.Tasks.Task<adresseSokResponse> adresseSokAsync(adresseSokRequest request);
    
    // CODEGEN: Generating message contract since the wrapper namespace (http://ws.ngisadrws.sk.hosledata.no) of message adresseSok2Request does not match the default value (https://ws.geonorge.no/SKWS2/services/Adresse)
    [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
    [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, Use=System.ServiceModel.OperationFormatUse.Encoded)]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(FylkeKomRec))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(FylkeRec))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(KommuneRecord))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(GateRecord))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(AdresseRecord2))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(AdresseRecord))]
    adresseSok2Response adresseSok2(adresseSok2Request request);
    
    [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
    System.Threading.Tasks.Task<adresseSok2Response> adresseSok2Async(adresseSok2Request request);
    
    // CODEGEN: Generating message contract since the wrapper namespace (http://ws.ngisadrws.sk.hosledata.no) of message gateSokRequest does not match the default value (https://ws.geonorge.no/SKWS2/services/Adresse)
    [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
    [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, Use=System.ServiceModel.OperationFormatUse.Encoded)]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(FylkeKomRec))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(FylkeRec))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(KommuneRecord))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(GateRecord))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(AdresseRecord2))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(AdresseRecord))]
    gateSokResponse gateSok(gateSokRequest request);
    
    [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
    System.Threading.Tasks.Task<gateSokResponse> gateSokAsync(gateSokRequest request);
    
    // CODEGEN: Generating message contract since the wrapper namespace (http://ws.ngisadrws.sk.hosledata.no) of message kommuneSokRequest does not match the default value (https://ws.geonorge.no/SKWS2/services/Adresse)
    [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
    [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, Use=System.ServiceModel.OperationFormatUse.Encoded)]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(FylkeKomRec))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(FylkeRec))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(KommuneRecord))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(GateRecord))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(AdresseRecord2))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(AdresseRecord))]
    kommuneSokResponse kommuneSok(kommuneSokRequest request);
    
    [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
    System.Threading.Tasks.Task<kommuneSokResponse> kommuneSokAsync(kommuneSokRequest request);
    
    // CODEGEN: Generating message contract since the wrapper namespace (http://ws.ngisadrws.sk.hosledata.no) of message fylkeSokRequest does not match the default value (https://ws.geonorge.no/SKWS2/services/Adresse)
    [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
    [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, Use=System.ServiceModel.OperationFormatUse.Encoded)]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(FylkeKomRec))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(FylkeRec))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(KommuneRecord))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(GateRecord))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(AdresseRecord2))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(AdresseRecord))]
    fylkeSokResponse fylkeSok(fylkeSokRequest request);
    
    [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
    System.Threading.Tasks.Task<fylkeSokResponse> fylkeSokAsync(fylkeSokRequest request);
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:adr2.ws.statkart.no")]
public partial class AdresseSokRes
{
    
    private AdresseRecord[] adresseRecordsField;
    
    private AdresseSokStatus sokStatusField;
    
    /// <remarks/>
    [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
    public AdresseRecord[] adresseRecords
    {
        get
        {
            return this.adresseRecordsField;
        }
        set
        {
            this.adresseRecordsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
    public AdresseSokStatus sokStatus
    {
        get
        {
            return this.sokStatusField;
        }
        set
        {
            this.sokStatusField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:adr2.ws.statkart.no")]
public partial class AdresseRecord
{
    
    private int adresseNrField;
    
    private int gateNrField;
    
    private string husBokstavField;
    
    private int husNrField;
    
    private int husUnderNrField;
    
    private int kommunenrField;
    
    private int postKretsNrField;
    
    private long punktNummerField;
    
    /// <remarks/>
    public int adresseNr
    {
        get
        {
            return this.adresseNrField;
        }
        set
        {
            this.adresseNrField = value;
        }
    }
    
    /// <remarks/>
    public int gateNr
    {
        get
        {
            return this.gateNrField;
        }
        set
        {
            this.gateNrField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
    public string husBokstav
    {
        get
        {
            return this.husBokstavField;
        }
        set
        {
            this.husBokstavField = value;
        }
    }
    
    /// <remarks/>
    public int husNr
    {
        get
        {
            return this.husNrField;
        }
        set
        {
            this.husNrField = value;
        }
    }
    
    /// <remarks/>
    public int husUnderNr
    {
        get
        {
            return this.husUnderNrField;
        }
        set
        {
            this.husUnderNrField = value;
        }
    }
    
    /// <remarks/>
    public int kommunenr
    {
        get
        {
            return this.kommunenrField;
        }
        set
        {
            this.kommunenrField = value;
        }
    }
    
    /// <remarks/>
    public int postKretsNr
    {
        get
        {
            return this.postKretsNrField;
        }
        set
        {
            this.postKretsNrField = value;
        }
    }
    
    /// <remarks/>
    public long punktNummer
    {
        get
        {
            return this.punktNummerField;
        }
        set
        {
            this.punktNummerField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:adr2.ws.statkart.no")]
public partial class SokStatus
{
    
    private string meldingField;
    
    private bool okField;
    
    /// <remarks/>
    [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
    public string melding
    {
        get
        {
            return this.meldingField;
        }
        set
        {
            this.meldingField = value;
        }
    }
    
    /// <remarks/>
    public bool ok
    {
        get
        {
            return this.okField;
        }
        set
        {
            this.okField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:adr2.ws.statkart.no")]
public partial class FylkeKomRec
{
    
    private string navnField;
    
    private int nrField;
    
    /// <remarks/>
    [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
    public string navn
    {
        get
        {
            return this.navnField;
        }
        set
        {
            this.navnField = value;
        }
    }
    
    /// <remarks/>
    public int nr
    {
        get
        {
            return this.nrField;
        }
        set
        {
            this.nrField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:adr2.ws.statkart.no")]
public partial class FylkeRec
{
    
    private FylkeKomRec[] komField;
    
    private string navnField;
    
    private int nrField;
    
    /// <remarks/>
    [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
    public FylkeKomRec[] kom
    {
        get
        {
            return this.komField;
        }
        set
        {
            this.komField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
    public string navn
    {
        get
        {
            return this.navnField;
        }
        set
        {
            this.navnField = value;
        }
    }
    
    /// <remarks/>
    public int nr
    {
        get
        {
            return this.nrField;
        }
        set
        {
            this.nrField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:adr2.ws.statkart.no")]
public partial class FylkeSokRes
{
    
    private FylkeRec[] fylkerField;
    
    private SokStatus statusField;
    
    /// <remarks/>
    [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
    public FylkeRec[] fylker
    {
        get
        {
            return this.fylkerField;
        }
        set
        {
            this.fylkerField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
    public SokStatus status
    {
        get
        {
            return this.statusField;
        }
        set
        {
            this.statusField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:adr2.ws.statkart.no")]
public partial class KommuneRecord
{
    
    private string fylkesnavnField;
    
    private string kommunenavnField;
    
    private int kommunenrField;
    
    /// <remarks/>
    [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
    public string fylkesnavn
    {
        get
        {
            return this.fylkesnavnField;
        }
        set
        {
            this.fylkesnavnField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
    public string kommunenavn
    {
        get
        {
            return this.kommunenavnField;
        }
        set
        {
            this.kommunenavnField = value;
        }
    }
    
    /// <remarks/>
    public int kommunenr
    {
        get
        {
            return this.kommunenrField;
        }
        set
        {
            this.kommunenrField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:adr2.ws.statkart.no")]
public partial class KommuneSokRes
{
    
    private KommuneRecord[] kommuneRecordsField;
    
    private AdresseSokStatus sokStatusField;
    
    /// <remarks/>
    [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
    public KommuneRecord[] kommuneRecords
    {
        get
        {
            return this.kommuneRecordsField;
        }
        set
        {
            this.kommuneRecordsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
    public AdresseSokStatus sokStatus
    {
        get
        {
            return this.sokStatusField;
        }
        set
        {
            this.sokStatusField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:adr2.ws.statkart.no")]
public partial class AdresseSokStatus
{
    
    private string meldingField;
    
    private bool mereDataField;
    
    private bool okField;
    
    /// <remarks/>
    [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
    public string melding
    {
        get
        {
            return this.meldingField;
        }
        set
        {
            this.meldingField = value;
        }
    }
    
    /// <remarks/>
    public bool mereData
    {
        get
        {
            return this.mereDataField;
        }
        set
        {
            this.mereDataField = value;
        }
    }
    
    /// <remarks/>
    public bool ok
    {
        get
        {
            return this.okField;
        }
        set
        {
            this.okField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:adr2.ws.statkart.no")]
public partial class GateRecord
{
    
    private string adresseTypeField;
    
    private string gateNavnField;
    
    private int gateNrField;
    
    private int kommunenrField;
    
    /// <remarks/>
    [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
    public string adresseType
    {
        get
        {
            return this.adresseTypeField;
        }
        set
        {
            this.adresseTypeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
    public string gateNavn
    {
        get
        {
            return this.gateNavnField;
        }
        set
        {
            this.gateNavnField = value;
        }
    }
    
    /// <remarks/>
    public int gateNr
    {
        get
        {
            return this.gateNrField;
        }
        set
        {
            this.gateNrField = value;
        }
    }
    
    /// <remarks/>
    public int kommunenr
    {
        get
        {
            return this.kommunenrField;
        }
        set
        {
            this.kommunenrField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:adr2.ws.statkart.no")]
public partial class GateSokRes
{
    
    private GateRecord[] gateRecordsField;
    
    private AdresseSokStatus sokStatusField;
    
    /// <remarks/>
    [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
    public GateRecord[] gateRecords
    {
        get
        {
            return this.gateRecordsField;
        }
        set
        {
            this.gateRecordsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
    public AdresseSokStatus sokStatus
    {
        get
        {
            return this.sokStatusField;
        }
        set
        {
            this.sokStatusField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:adr2.ws.statkart.no")]
public partial class AdresseRecord2
{
    
    private string gateNavnField;
    
    private int gateNrField;
    
    private string husBokstavField;
    
    private int husNrField;
    
    private int husUnderNrField;
    
    private string kommunenavnField;
    
    private int kommunenrField;
    
    private int koordinatSystemField;
    
    private string postKretsNavnField;
    
    private int postKretsNrField;
    
    private double xKoordinatField;
    
    private double yKoordinatField;
    
    private double zKoordinatField;
    
    /// <remarks/>
    [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
    public string gateNavn
    {
        get
        {
            return this.gateNavnField;
        }
        set
        {
            this.gateNavnField = value;
        }
    }
    
    /// <remarks/>
    public int gateNr
    {
        get
        {
            return this.gateNrField;
        }
        set
        {
            this.gateNrField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
    public string husBokstav
    {
        get
        {
            return this.husBokstavField;
        }
        set
        {
            this.husBokstavField = value;
        }
    }
    
    /// <remarks/>
    public int husNr
    {
        get
        {
            return this.husNrField;
        }
        set
        {
            this.husNrField = value;
        }
    }
    
    /// <remarks/>
    public int husUnderNr
    {
        get
        {
            return this.husUnderNrField;
        }
        set
        {
            this.husUnderNrField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
    public string kommunenavn
    {
        get
        {
            return this.kommunenavnField;
        }
        set
        {
            this.kommunenavnField = value;
        }
    }
    
    /// <remarks/>
    public int kommunenr
    {
        get
        {
            return this.kommunenrField;
        }
        set
        {
            this.kommunenrField = value;
        }
    }
    
    /// <remarks/>
    public int koordinatSystem
    {
        get
        {
            return this.koordinatSystemField;
        }
        set
        {
            this.koordinatSystemField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
    public string postKretsNavn
    {
        get
        {
            return this.postKretsNavnField;
        }
        set
        {
            this.postKretsNavnField = value;
        }
    }
    
    /// <remarks/>
    public int postKretsNr
    {
        get
        {
            return this.postKretsNrField;
        }
        set
        {
            this.postKretsNrField = value;
        }
    }
    
    /// <remarks/>
    public double xKoordinat
    {
        get
        {
            return this.xKoordinatField;
        }
        set
        {
            this.xKoordinatField = value;
        }
    }
    
    /// <remarks/>
    public double yKoordinat
    {
        get
        {
            return this.yKoordinatField;
        }
        set
        {
            this.yKoordinatField = value;
        }
    }
    
    /// <remarks/>
    public double zKoordinat
    {
        get
        {
            return this.zKoordinatField;
        }
        set
        {
            this.zKoordinatField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:adr2.ws.statkart.no")]
public partial class AdresseSokRes2
{
    
    private AdresseRecord2[] adresseRecords2Field;
    
    private AdresseSokStatus sokStatusField;
    
    /// <remarks/>
    [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
    public AdresseRecord2[] adresseRecords2
    {
        get
        {
            return this.adresseRecords2Field;
        }
        set
        {
            this.adresseRecords2Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
    public AdresseSokStatus sokStatus
    {
        get
        {
            return this.sokStatusField;
        }
        set
        {
            this.sokStatusField = value;
        }
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(WrapperName="adresseSok", WrapperNamespace="http://ws.ngisadrws.sk.hosledata.no", IsWrapped=true)]
public partial class adresseSokRequest
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
    public string brukerid;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
    public string passord;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
    public string aliasId;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=3)]
    public int kommuneNr;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=4)]
    public int gateNr;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=5)]
    public int husNrMin;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=6)]
    public int husNrMax;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=7)]
    public string husBokstavFra;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=8)]
    public string husBokstavTil;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=9)]
    public int husUnderNrMin;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=10)]
    public int husUnderNrMax;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=11)]
    public int maxAnt;
    
    public adresseSokRequest()
    {
    }
    
    public adresseSokRequest(string brukerid, string passord, string aliasId, int kommuneNr, int gateNr, int husNrMin, int husNrMax, string husBokstavFra, string husBokstavTil, int husUnderNrMin, int husUnderNrMax, int maxAnt)
    {
        this.brukerid = brukerid;
        this.passord = passord;
        this.aliasId = aliasId;
        this.kommuneNr = kommuneNr;
        this.gateNr = gateNr;
        this.husNrMin = husNrMin;
        this.husNrMax = husNrMax;
        this.husBokstavFra = husBokstavFra;
        this.husBokstavTil = husBokstavTil;
        this.husUnderNrMin = husUnderNrMin;
        this.husUnderNrMax = husUnderNrMax;
        this.maxAnt = maxAnt;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(WrapperName="adresseSokResponse", WrapperNamespace="https://ws.geonorge.no/SKWS2/services/Adresse", IsWrapped=true)]
public partial class adresseSokResponse
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
    public AdresseSokRes adresseSokReturn;
    
    public adresseSokResponse()
    {
    }
    
    public adresseSokResponse(AdresseSokRes adresseSokReturn)
    {
        this.adresseSokReturn = adresseSokReturn;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(WrapperName="adresseSok2", WrapperNamespace="http://ws.ngisadrws.sk.hosledata.no", IsWrapped=true)]
public partial class adresseSok2Request
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
    public string brukerid;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
    public string passord;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
    public string aliasId;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=3)]
    public int kommuneNrMin;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=4)]
    public int kommuneNrMax;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=5)]
    public string kommuneNavn;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=6)]
    public int gateNrMin;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=7)]
    public int gateNrMax;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=8)]
    public string gateNavn;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=9)]
    public string adresseType;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=10)]
    public int husNrMin;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=11)]
    public int husNrMax;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=12)]
    public string husBokstavFra;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=13)]
    public string husBokstavTil;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=14)]
    public int husUnderNrMin;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=15)]
    public int husUnderNrMax;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=16)]
    public int maxAnt;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=17)]
    public int tilSosiKoordSyst;
    
    public adresseSok2Request()
    {
    }
    
    public adresseSok2Request(
                string brukerid, 
                string passord, 
                string aliasId, 
                int kommuneNrMin, 
                int kommuneNrMax, 
                string kommuneNavn, 
                int gateNrMin, 
                int gateNrMax, 
                string gateNavn, 
                string adresseType, 
                int husNrMin, 
                int husNrMax, 
                string husBokstavFra, 
                string husBokstavTil, 
                int husUnderNrMin, 
                int husUnderNrMax, 
                int maxAnt, 
                int tilSosiKoordSyst)
    {
        this.brukerid = brukerid;
        this.passord = passord;
        this.aliasId = aliasId;
        this.kommuneNrMin = kommuneNrMin;
        this.kommuneNrMax = kommuneNrMax;
        this.kommuneNavn = kommuneNavn;
        this.gateNrMin = gateNrMin;
        this.gateNrMax = gateNrMax;
        this.gateNavn = gateNavn;
        this.adresseType = adresseType;
        this.husNrMin = husNrMin;
        this.husNrMax = husNrMax;
        this.husBokstavFra = husBokstavFra;
        this.husBokstavTil = husBokstavTil;
        this.husUnderNrMin = husUnderNrMin;
        this.husUnderNrMax = husUnderNrMax;
        this.maxAnt = maxAnt;
        this.tilSosiKoordSyst = tilSosiKoordSyst;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(WrapperName="adresseSok2Response", WrapperNamespace="https://ws.geonorge.no/SKWS2/services/Adresse", IsWrapped=true)]
public partial class adresseSok2Response
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
    public AdresseSokRes2 adresseSok2Return;
    
    public adresseSok2Response()
    {
    }
    
    public adresseSok2Response(AdresseSokRes2 adresseSok2Return)
    {
        this.adresseSok2Return = adresseSok2Return;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(WrapperName="gateSok", WrapperNamespace="http://ws.ngisadrws.sk.hosledata.no", IsWrapped=true)]
public partial class gateSokRequest
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
    public string brukerid;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
    public string passord;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
    public string aliasId;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=3)]
    public int kommuneNrMin;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=4)]
    public int kommuneNrMax;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=5)]
    public int gateNrMin;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=6)]
    public int gateNrMax;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=7)]
    public string gateNavn;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=8)]
    public string adresseType;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=9)]
    public int maxAnt;
    
    public gateSokRequest()
    {
    }
    
    public gateSokRequest(string brukerid, string passord, string aliasId, int kommuneNrMin, int kommuneNrMax, int gateNrMin, int gateNrMax, string gateNavn, string adresseType, int maxAnt)
    {
        this.brukerid = brukerid;
        this.passord = passord;
        this.aliasId = aliasId;
        this.kommuneNrMin = kommuneNrMin;
        this.kommuneNrMax = kommuneNrMax;
        this.gateNrMin = gateNrMin;
        this.gateNrMax = gateNrMax;
        this.gateNavn = gateNavn;
        this.adresseType = adresseType;
        this.maxAnt = maxAnt;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(WrapperName="gateSokResponse", WrapperNamespace="https://ws.geonorge.no/SKWS2/services/Adresse", IsWrapped=true)]
public partial class gateSokResponse
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
    public GateSokRes gateSokReturn;
    
    public gateSokResponse()
    {
    }
    
    public gateSokResponse(GateSokRes gateSokReturn)
    {
        this.gateSokReturn = gateSokReturn;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(WrapperName="kommuneSok", WrapperNamespace="http://ws.ngisadrws.sk.hosledata.no", IsWrapped=true)]
public partial class kommuneSokRequest
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
    public string brukerid;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
    public string passord;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
    public string aliasId;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=3)]
    public int kommuneNrMin;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=4)]
    public int kommuneNrMax;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=5)]
    public string kommuneNavn;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=6)]
    public int maxAnt;
    
    public kommuneSokRequest()
    {
    }
    
    public kommuneSokRequest(string brukerid, string passord, string aliasId, int kommuneNrMin, int kommuneNrMax, string kommuneNavn, int maxAnt)
    {
        this.brukerid = brukerid;
        this.passord = passord;
        this.aliasId = aliasId;
        this.kommuneNrMin = kommuneNrMin;
        this.kommuneNrMax = kommuneNrMax;
        this.kommuneNavn = kommuneNavn;
        this.maxAnt = maxAnt;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(WrapperName="kommuneSokResponse", WrapperNamespace="https://ws.geonorge.no/SKWS2/services/Adresse", IsWrapped=true)]
public partial class kommuneSokResponse
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
    public KommuneSokRes kommuneSokReturn;
    
    public kommuneSokResponse()
    {
    }
    
    public kommuneSokResponse(KommuneSokRes kommuneSokReturn)
    {
        this.kommuneSokReturn = kommuneSokReturn;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(WrapperName="fylkeSok", WrapperNamespace="http://ws.ngisadrws.sk.hosledata.no", IsWrapped=true)]
public partial class fylkeSokRequest
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
    public string brukerid;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
    public string passord;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
    public string aliasId;
    
    public fylkeSokRequest()
    {
    }
    
    public fylkeSokRequest(string brukerid, string passord, string aliasId)
    {
        this.brukerid = brukerid;
        this.passord = passord;
        this.aliasId = aliasId;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(WrapperName="fylkeSokResponse", WrapperNamespace="https://ws.geonorge.no/SKWS2/services/Adresse", IsWrapped=true)]
public partial class fylkeSokResponse
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
    public FylkeSokRes fylkeSokReturn;
    
    public fylkeSokResponse()
    {
    }
    
    public fylkeSokResponse(FylkeSokRes fylkeSokReturn)
    {
        this.fylkeSokReturn = fylkeSokReturn;
    }
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface AdresseChannel : Adresse, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class AdresseClient : System.ServiceModel.ClientBase<Adresse>, Adresse
{
    
    public AdresseClient()
    {
    }
    
    public AdresseClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public AdresseClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public AdresseClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public AdresseClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    adresseSokResponse Adresse.adresseSok(adresseSokRequest request)
    {
        return base.Channel.adresseSok(request);
    }
    
    public AdresseSokRes adresseSok(string brukerid, string passord, string aliasId, int kommuneNr, int gateNr, int husNrMin, int husNrMax, string husBokstavFra, string husBokstavTil, int husUnderNrMin, int husUnderNrMax, int maxAnt)
    {
        adresseSokRequest inValue = new adresseSokRequest();
        inValue.brukerid = brukerid;
        inValue.passord = passord;
        inValue.aliasId = aliasId;
        inValue.kommuneNr = kommuneNr;
        inValue.gateNr = gateNr;
        inValue.husNrMin = husNrMin;
        inValue.husNrMax = husNrMax;
        inValue.husBokstavFra = husBokstavFra;
        inValue.husBokstavTil = husBokstavTil;
        inValue.husUnderNrMin = husUnderNrMin;
        inValue.husUnderNrMax = husUnderNrMax;
        inValue.maxAnt = maxAnt;
        adresseSokResponse retVal = ((Adresse)(this)).adresseSok(inValue);
        return retVal.adresseSokReturn;
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    System.Threading.Tasks.Task<adresseSokResponse> Adresse.adresseSokAsync(adresseSokRequest request)
    {
        return base.Channel.adresseSokAsync(request);
    }
    
    public System.Threading.Tasks.Task<adresseSokResponse> adresseSokAsync(string brukerid, string passord, string aliasId, int kommuneNr, int gateNr, int husNrMin, int husNrMax, string husBokstavFra, string husBokstavTil, int husUnderNrMin, int husUnderNrMax, int maxAnt)
    {
        adresseSokRequest inValue = new adresseSokRequest();
        inValue.brukerid = brukerid;
        inValue.passord = passord;
        inValue.aliasId = aliasId;
        inValue.kommuneNr = kommuneNr;
        inValue.gateNr = gateNr;
        inValue.husNrMin = husNrMin;
        inValue.husNrMax = husNrMax;
        inValue.husBokstavFra = husBokstavFra;
        inValue.husBokstavTil = husBokstavTil;
        inValue.husUnderNrMin = husUnderNrMin;
        inValue.husUnderNrMax = husUnderNrMax;
        inValue.maxAnt = maxAnt;
        return ((Adresse)(this)).adresseSokAsync(inValue);
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    adresseSok2Response Adresse.adresseSok2(adresseSok2Request request)
    {
        return base.Channel.adresseSok2(request);
    }
    
    public AdresseSokRes2 adresseSok2(
                string brukerid, 
                string passord, 
                string aliasId, 
                int kommuneNrMin, 
                int kommuneNrMax, 
                string kommuneNavn, 
                int gateNrMin, 
                int gateNrMax, 
                string gateNavn, 
                string adresseType, 
                int husNrMin, 
                int husNrMax, 
                string husBokstavFra, 
                string husBokstavTil, 
                int husUnderNrMin, 
                int husUnderNrMax, 
                int maxAnt, 
                int tilSosiKoordSyst)
    {
        adresseSok2Request inValue = new adresseSok2Request();
        inValue.brukerid = brukerid;
        inValue.passord = passord;
        inValue.aliasId = aliasId;
        inValue.kommuneNrMin = kommuneNrMin;
        inValue.kommuneNrMax = kommuneNrMax;
        inValue.kommuneNavn = kommuneNavn;
        inValue.gateNrMin = gateNrMin;
        inValue.gateNrMax = gateNrMax;
        inValue.gateNavn = gateNavn;
        inValue.adresseType = adresseType;
        inValue.husNrMin = husNrMin;
        inValue.husNrMax = husNrMax;
        inValue.husBokstavFra = husBokstavFra;
        inValue.husBokstavTil = husBokstavTil;
        inValue.husUnderNrMin = husUnderNrMin;
        inValue.husUnderNrMax = husUnderNrMax;
        inValue.maxAnt = maxAnt;
        inValue.tilSosiKoordSyst = tilSosiKoordSyst;
        adresseSok2Response retVal = ((Adresse)(this)).adresseSok2(inValue);
        return retVal.adresseSok2Return;
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    System.Threading.Tasks.Task<adresseSok2Response> Adresse.adresseSok2Async(adresseSok2Request request)
    {
        return base.Channel.adresseSok2Async(request);
    }
    
    public System.Threading.Tasks.Task<adresseSok2Response> adresseSok2Async(
                string brukerid, 
                string passord, 
                string aliasId, 
                int kommuneNrMin, 
                int kommuneNrMax, 
                string kommuneNavn, 
                int gateNrMin, 
                int gateNrMax, 
                string gateNavn, 
                string adresseType, 
                int husNrMin, 
                int husNrMax, 
                string husBokstavFra, 
                string husBokstavTil, 
                int husUnderNrMin, 
                int husUnderNrMax, 
                int maxAnt, 
                int tilSosiKoordSyst)
    {
        adresseSok2Request inValue = new adresseSok2Request();
        inValue.brukerid = brukerid;
        inValue.passord = passord;
        inValue.aliasId = aliasId;
        inValue.kommuneNrMin = kommuneNrMin;
        inValue.kommuneNrMax = kommuneNrMax;
        inValue.kommuneNavn = kommuneNavn;
        inValue.gateNrMin = gateNrMin;
        inValue.gateNrMax = gateNrMax;
        inValue.gateNavn = gateNavn;
        inValue.adresseType = adresseType;
        inValue.husNrMin = husNrMin;
        inValue.husNrMax = husNrMax;
        inValue.husBokstavFra = husBokstavFra;
        inValue.husBokstavTil = husBokstavTil;
        inValue.husUnderNrMin = husUnderNrMin;
        inValue.husUnderNrMax = husUnderNrMax;
        inValue.maxAnt = maxAnt;
        inValue.tilSosiKoordSyst = tilSosiKoordSyst;
        return ((Adresse)(this)).adresseSok2Async(inValue);
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    gateSokResponse Adresse.gateSok(gateSokRequest request)
    {
        return base.Channel.gateSok(request);
    }
    
    public GateSokRes gateSok(string brukerid, string passord, string aliasId, int kommuneNrMin, int kommuneNrMax, int gateNrMin, int gateNrMax, string gateNavn, string adresseType, int maxAnt)
    {
        gateSokRequest inValue = new gateSokRequest();
        inValue.brukerid = brukerid;
        inValue.passord = passord;
        inValue.aliasId = aliasId;
        inValue.kommuneNrMin = kommuneNrMin;
        inValue.kommuneNrMax = kommuneNrMax;
        inValue.gateNrMin = gateNrMin;
        inValue.gateNrMax = gateNrMax;
        inValue.gateNavn = gateNavn;
        inValue.adresseType = adresseType;
        inValue.maxAnt = maxAnt;
        gateSokResponse retVal = ((Adresse)(this)).gateSok(inValue);
        return retVal.gateSokReturn;
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    System.Threading.Tasks.Task<gateSokResponse> Adresse.gateSokAsync(gateSokRequest request)
    {
        return base.Channel.gateSokAsync(request);
    }
    
    public System.Threading.Tasks.Task<gateSokResponse> gateSokAsync(string brukerid, string passord, string aliasId, int kommuneNrMin, int kommuneNrMax, int gateNrMin, int gateNrMax, string gateNavn, string adresseType, int maxAnt)
    {
        gateSokRequest inValue = new gateSokRequest();
        inValue.brukerid = brukerid;
        inValue.passord = passord;
        inValue.aliasId = aliasId;
        inValue.kommuneNrMin = kommuneNrMin;
        inValue.kommuneNrMax = kommuneNrMax;
        inValue.gateNrMin = gateNrMin;
        inValue.gateNrMax = gateNrMax;
        inValue.gateNavn = gateNavn;
        inValue.adresseType = adresseType;
        inValue.maxAnt = maxAnt;
        return ((Adresse)(this)).gateSokAsync(inValue);
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    kommuneSokResponse Adresse.kommuneSok(kommuneSokRequest request)
    {
        return base.Channel.kommuneSok(request);
    }
    
    public KommuneSokRes kommuneSok(string brukerid, string passord, string aliasId, int kommuneNrMin, int kommuneNrMax, string kommuneNavn, int maxAnt)
    {
        kommuneSokRequest inValue = new kommuneSokRequest();
        inValue.brukerid = brukerid;
        inValue.passord = passord;
        inValue.aliasId = aliasId;
        inValue.kommuneNrMin = kommuneNrMin;
        inValue.kommuneNrMax = kommuneNrMax;
        inValue.kommuneNavn = kommuneNavn;
        inValue.maxAnt = maxAnt;
        kommuneSokResponse retVal = ((Adresse)(this)).kommuneSok(inValue);
        return retVal.kommuneSokReturn;
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    System.Threading.Tasks.Task<kommuneSokResponse> Adresse.kommuneSokAsync(kommuneSokRequest request)
    {
        return base.Channel.kommuneSokAsync(request);
    }
    
    public System.Threading.Tasks.Task<kommuneSokResponse> kommuneSokAsync(string brukerid, string passord, string aliasId, int kommuneNrMin, int kommuneNrMax, string kommuneNavn, int maxAnt)
    {
        kommuneSokRequest inValue = new kommuneSokRequest();
        inValue.brukerid = brukerid;
        inValue.passord = passord;
        inValue.aliasId = aliasId;
        inValue.kommuneNrMin = kommuneNrMin;
        inValue.kommuneNrMax = kommuneNrMax;
        inValue.kommuneNavn = kommuneNavn;
        inValue.maxAnt = maxAnt;
        return ((Adresse)(this)).kommuneSokAsync(inValue);
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    fylkeSokResponse Adresse.fylkeSok(fylkeSokRequest request)
    {
        return base.Channel.fylkeSok(request);
    }
    
    public FylkeSokRes fylkeSok(string brukerid, string passord, string aliasId)
    {
        fylkeSokRequest inValue = new fylkeSokRequest();
        inValue.brukerid = brukerid;
        inValue.passord = passord;
        inValue.aliasId = aliasId;
        fylkeSokResponse retVal = ((Adresse)(this)).fylkeSok(inValue);
        return retVal.fylkeSokReturn;
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    System.Threading.Tasks.Task<fylkeSokResponse> Adresse.fylkeSokAsync(fylkeSokRequest request)
    {
        return base.Channel.fylkeSokAsync(request);
    }
    
    public System.Threading.Tasks.Task<fylkeSokResponse> fylkeSokAsync(string brukerid, string passord, string aliasId)
    {
        fylkeSokRequest inValue = new fylkeSokRequest();
        inValue.brukerid = brukerid;
        inValue.passord = passord;
        inValue.aliasId = aliasId;
        return ((Adresse)(this)).fylkeSokAsync(inValue);
    }
}
