//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: System.Runtime.Serialization.ContractNamespaceAttribute("http://rep.geointegrasjon.no/Matrikkel/Felles/xml.schema/2012.01.31", ClrNamespace="rep.geointegrasjon.no.Matrikkel.Felles.xml.schema._2012._01._31")]
[assembly: System.Runtime.Serialization.ContractNamespaceAttribute("http://rep.geointegrasjon.no/Felles/Teknisk/xml.schema/2012.01.31", ClrNamespace="rep.geointegrasjon.no.Felles.Teknisk.xml.schema._2012._01._31")]
[assembly: System.Runtime.Serialization.ContractNamespaceAttribute("http://rep.geointegrasjon.no/Felles/Geometri/xml.schema/2012.01.31", ClrNamespace="rep.geointegrasjon.no.Felles.Geometri.xml.schema._2012._01._31")]
[assembly: System.Runtime.Serialization.ContractNamespaceAttribute("http://rep.geointegrasjon.no/Felles/Kodeliste/xml.schema/2012.01.31", ClrNamespace="rep.geointegrasjon.no.Felles.Kodeliste.xml.schema._2012._01._31")]
[assembly: System.Runtime.Serialization.ContractNamespaceAttribute("http://rep.geointegrasjon.no/Felles/Kontakt/xml.schema/2012.01.31", ClrNamespace="rep.geointegrasjon.no.Felles.Kontakt.xml.schema._2012._01._31")]
[assembly: System.Runtime.Serialization.ContractNamespaceAttribute("http://rep.geointegrasjon.no/Sak/Faser/xml.schema/2012.01.31", ClrNamespace="rep.geointegrasjon.no.Sak.Faser.xml.schema._2012._01._31")]
[assembly: System.Runtime.Serialization.ContractNamespaceAttribute("http://rep.geointegrasjon.no/Arkiv/Dokument/xml.schema/2012.01.31", ClrNamespace="rep.geointegrasjon.no.Arkiv.Dokument.xml.schema._2012._01._31")]
[assembly: System.Runtime.Serialization.ContractNamespaceAttribute("http://rep.geointegrasjon.no/Plan/Utvidet/xml.schema/2012.01.31", ClrNamespace="rep.geointegrasjon.no.Plan.Utvidet.xml.schema._2012._01._31")]
[assembly: System.Runtime.Serialization.ContractNamespaceAttribute("http://rep.geointegrasjon.no/Felles/Adresse/xml.schema/2012.01.31", ClrNamespace="rep.geointegrasjon.no.Felles.Adresse.xml.schema._2012._01._31")]
[assembly: System.Runtime.Serialization.ContractNamespaceAttribute("http://rep.geointegrasjon.no/Arkiv/Kjerne/xml.schema/2012.01.31", ClrNamespace="rep.geointegrasjon.no.Arkiv.Kjerne.xml.schema._2012._01._31")]
[assembly: System.Runtime.Serialization.ContractNamespaceAttribute("http://rep.geointegrasjon.no/Matrikkel/Basis/xml.schema/2012.01.31", ClrNamespace="rep.geointegrasjon.no.Matrikkel.Basis.xml.schema._2012._01._31")]
[assembly: System.Runtime.Serialization.ContractNamespaceAttribute("http://rep.geointegrasjon.no/Plan/Basis/xml.schema/2012.01.31", ClrNamespace="rep.geointegrasjon.no.Plan.Basis.xml.schema._2012._01._31")]
[assembly: System.Runtime.Serialization.ContractNamespaceAttribute("http://rep.geointegrasjon.no/Matrikkel/Utvidet/xml.schema/2012.01.31", ClrNamespace="rep.geointegrasjon.no.Matrikkel.Utvidet.xml.schema._2012._01._31")]

namespace rep.geointegrasjon.no.Matrikkel.Felles.xml.schema._2012._01._31
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Matrikkelnummer", Namespace="http://rep.geointegrasjon.no/Matrikkel/Felles/xml.schema/2012.01.31")]
    public partial class Matrikkelnummer : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string kommunenummerField;
        
        private long gaardsnummerField;
        
        private long bruksnummerField;
        
        private long festenummerField;
        
        private long seksjonsnummerField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false)]
        public string kommunenummer
        {
            get
            {
                return this.kommunenummerField;
            }
            set
            {
                this.kommunenummerField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public long gaardsnummer
        {
            get
            {
                return this.gaardsnummerField;
            }
            set
            {
                this.gaardsnummerField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public long bruksnummer
        {
            get
            {
                return this.bruksnummerField;
            }
            set
            {
                this.bruksnummerField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public long festenummer
        {
            get
            {
                return this.festenummerField;
            }
            set
            {
                this.festenummerField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public long seksjonsnummer
        {
            get
            {
                return this.seksjonsnummerField;
            }
            set
            {
                this.seksjonsnummerField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="MatrikkelnummerListe", Namespace="http://rep.geointegrasjon.no/Matrikkel/Felles/xml.schema/2012.01.31", ItemName="liste")]
    public class MatrikkelnummerListe : System.Collections.Generic.List<rep.geointegrasjon.no.Matrikkel.Felles.xml.schema._2012._01._31.Matrikkelnummer>
    {
    }
}
namespace rep.geointegrasjon.no.Felles.Teknisk.xml.schema._2012._01._31
{
    using System.Runtime.Serialization;
    using System.Xml;

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Kontekst", Namespace="http://rep.geointegrasjon.no/Felles/Teknisk/xml.schema/2012.01.31")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(rep.geointegrasjon.no.Felles.Teknisk.xml.schema._2012._01._31.ArkivKontekst))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(rep.geointegrasjon.no.Felles.Teknisk.xml.schema._2012._01._31.PlanKontekst))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(rep.geointegrasjon.no.Felles.Teknisk.xml.schema._2012._01._31.MatrikkelKontekst))]
    public partial class Kontekst : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string spraakField;
        
        private string klientnavnField;
        
        private string klientversjonField;
        
        private string systemversjonField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string spraak
        {
            get
            {
                return this.spraakField;
            }
            set
            {
                this.spraakField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string klientnavn
        {
            get
            {
                return this.klientnavnField;
            }
            set
            {
                this.klientnavnField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string klientversjon
        {
            get
            {
                return this.klientversjonField;
            }
            set
            {
                this.klientversjonField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string systemversjon
        {
            get
            {
                return this.systemversjonField;
            }
            set
            {
                this.systemversjonField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ArkivKontekst", Namespace="http://rep.geointegrasjon.no/Felles/Teknisk/xml.schema/2012.01.31")]
    public partial class ArkivKontekst : rep.geointegrasjon.no.Felles.Teknisk.xml.schema._2012._01._31.Kontekst
    {
        
        private rep.geointegrasjon.no.Felles.Geometri.xml.schema._2012._01._31.KoordinatsystemKode koordinatsystemField;
        
        private string referanseoppsettField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public rep.geointegrasjon.no.Felles.Geometri.xml.schema._2012._01._31.KoordinatsystemKode koordinatsystem
        {
            get
            {
                return this.koordinatsystemField;
            }
            set
            {
                this.koordinatsystemField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string referanseoppsett
        {
            get
            {
                return this.referanseoppsettField;
            }
            set
            {
                this.referanseoppsettField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PlanKontekst", Namespace="http://rep.geointegrasjon.no/Felles/Teknisk/xml.schema/2012.01.31")]
    public partial class PlanKontekst : rep.geointegrasjon.no.Felles.Teknisk.xml.schema._2012._01._31.Kontekst
    {
        
        private rep.geointegrasjon.no.Felles.Geometri.xml.schema._2012._01._31.KoordinatsystemKode koordinatsystemField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public rep.geointegrasjon.no.Felles.Geometri.xml.schema._2012._01._31.KoordinatsystemKode koordinatsystem
        {
            get
            {
                return this.koordinatsystemField;
            }
            set
            {
                this.koordinatsystemField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MatrikkelKontekst", Namespace="http://rep.geointegrasjon.no/Felles/Teknisk/xml.schema/2012.01.31")]
    public partial class MatrikkelKontekst : rep.geointegrasjon.no.Felles.Teknisk.xml.schema._2012._01._31.Kontekst
    {
        
        private rep.geointegrasjon.no.Felles.Geometri.xml.schema._2012._01._31.KoordinatsystemKode koordinatsystemField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public rep.geointegrasjon.no.Felles.Geometri.xml.schema._2012._01._31.KoordinatsystemKode koordinatsystem
        {
            get
            {
                return this.koordinatsystemField;
            }
            set
            {
                this.koordinatsystemField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GeointegrasjonFault", Namespace="http://rep.geointegrasjon.no/Felles/Teknisk/xml.schema/2012.01.31")]
    public partial class GeointegrasjonFault : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string feilKodeField;
        
        private string feilBeskrivelseField;
        
        private rep.geointegrasjon.no.Felles.Teknisk.xml.schema._2012._01._31.StringListe feilDetaljerField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false)]
        public string feilKode
        {
            get
            {
                return this.feilKodeField;
            }
            set
            {
                this.feilKodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string feilBeskrivelse
        {
            get
            {
                return this.feilBeskrivelseField;
            }
            set
            {
                this.feilBeskrivelseField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public rep.geointegrasjon.no.Felles.Teknisk.xml.schema._2012._01._31.StringListe feilDetaljer
        {
            get
            {
                return this.feilDetaljerField;
            }
            set
            {
                this.feilDetaljerField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="StringListe", Namespace="http://rep.geointegrasjon.no/Felles/Teknisk/xml.schema/2012.01.31", ItemName="liste")]
    public class StringListe : System.Collections.Generic.List<string>
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Xml.Serialization.XmlSchemaProviderAttribute("ExportSchema")]
    [System.Xml.Serialization.XmlRootAttribute(IsNullable=false)]
    public partial class SystemFault : object, System.Xml.Serialization.IXmlSerializable
    {
        
        private System.Xml.XmlNode[] nodesField;
        
        private static System.Xml.XmlQualifiedName typeName = new System.Xml.XmlQualifiedName("SystemFault", "http://rep.geointegrasjon.no/Felles/Teknisk/xml.schema/2012.01.31");
        
        public System.Xml.XmlNode[] Nodes
        {
            get
            {
                return this.nodesField;
            }
            set
            {
                this.nodesField = value;
            }
        }
        
        public void ReadXml(System.Xml.XmlReader reader)
        {
            this.nodesField = System.Runtime.Serialization.XmlSerializableServices.ReadNodes(reader);
        }
        
        public void WriteXml(System.Xml.XmlWriter writer)
        {
            System.Runtime.Serialization.XmlSerializableServices.WriteNodes(writer, this.Nodes);
        }
        
        public System.Xml.Schema.XmlSchema GetSchema()
        {
            return null;
        }
        
        public static System.Xml.XmlQualifiedName ExportSchema(System.Xml.Schema.XmlSchemaSet schemas)
        {
            System.Runtime.Serialization.XmlSerializableServices.AddDefaultSchema(schemas, typeName);
            return typeName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Xml.Serialization.XmlSchemaProviderAttribute("ExportSchema")]
    [System.Xml.Serialization.XmlRootAttribute(IsNullable=false)]
    public partial class ApplicationFault : object, System.Xml.Serialization.IXmlSerializable
    {
        
        private System.Xml.XmlNode[] nodesField;
        
        private static System.Xml.XmlQualifiedName typeName = new System.Xml.XmlQualifiedName("ApplicationFault", "http://rep.geointegrasjon.no/Felles/Teknisk/xml.schema/2012.01.31");
        
        public System.Xml.XmlNode[] Nodes
        {
            get
            {
                return this.nodesField;
            }
            set
            {
                this.nodesField = value;
            }
        }
        
        public void ReadXml(System.Xml.XmlReader reader)
        {
            this.nodesField = System.Runtime.Serialization.XmlSerializableServices.ReadNodes(reader);
        }
        
        public void WriteXml(System.Xml.XmlWriter writer)
        {
            System.Runtime.Serialization.XmlSerializableServices.WriteNodes(writer, this.Nodes);
        }
        
        public System.Xml.Schema.XmlSchema GetSchema()
        {
            return null;
        }
        
        public static System.Xml.XmlQualifiedName ExportSchema(System.Xml.Schema.XmlSchemaSet schemas)
        {
            System.Runtime.Serialization.XmlSerializableServices.AddDefaultSchema(schemas, typeName);
            return typeName;
        }
    }
}
namespace rep.geointegrasjon.no.Felles.Geometri.xml.schema._2012._01._31
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="KoordinatsystemKode", Namespace="http://rep.geointegrasjon.no/Felles/Geometri/xml.schema/2012.01.31")]
    public partial class KoordinatsystemKode : rep.geointegrasjon.no.Felles.Kodeliste.xml.schema._2012._01._31.Kode
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="OmraadeListe", Namespace="http://rep.geointegrasjon.no/Felles/Geometri/xml.schema/2012.01.31", ItemName="liste")]
    public class OmraadeListe : System.Collections.Generic.List<rep.geointegrasjon.no.Felles.Geometri.xml.schema._2012._01._31.Omraade>
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Omraade", Namespace="http://rep.geointegrasjon.no/Felles/Geometri/xml.schema/2012.01.31")]
    public partial class Omraade : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private rep.geointegrasjon.no.Felles.Geometri.xml.schema._2012._01._31.Punkt punktField;
        
        private rep.geointegrasjon.no.Felles.Geometri.xml.schema._2012._01._31.Flate flateField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public rep.geointegrasjon.no.Felles.Geometri.xml.schema._2012._01._31.Punkt punkt
        {
            get
            {
                return this.punktField;
            }
            set
            {
                this.punktField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public rep.geointegrasjon.no.Felles.Geometri.xml.schema._2012._01._31.Flate flate
        {
            get
            {
                return this.flateField;
            }
            set
            {
                this.flateField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Punkt", Namespace="http://rep.geointegrasjon.no/Felles/Geometri/xml.schema/2012.01.31")]
    public partial class Punkt : rep.geointegrasjon.no.Felles.Geometri.xml.schema._2012._01._31.Geometri
    {
        
        private rep.geointegrasjon.no.Felles.Geometri.xml.schema._2012._01._31.Koordinat posisjonField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false)]
        public rep.geointegrasjon.no.Felles.Geometri.xml.schema._2012._01._31.Koordinat posisjon
        {
            get
            {
                return this.posisjonField;
            }
            set
            {
                this.posisjonField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Flate", Namespace="http://rep.geointegrasjon.no/Felles/Geometri/xml.schema/2012.01.31")]
    public partial class Flate : rep.geointegrasjon.no.Felles.Geometri.xml.schema._2012._01._31.Geometri
    {
        
        private rep.geointegrasjon.no.Felles.Geometri.xml.schema._2012._01._31.RingListe indreAvgrensningField;
        
        private rep.geointegrasjon.no.Felles.Geometri.xml.schema._2012._01._31.Ring ytreAvgrensningField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public rep.geointegrasjon.no.Felles.Geometri.xml.schema._2012._01._31.RingListe indreAvgrensning
        {
            get
            {
                return this.indreAvgrensningField;
            }
            set
            {
                this.indreAvgrensningField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false)]
        public rep.geointegrasjon.no.Felles.Geometri.xml.schema._2012._01._31.Ring ytreAvgrensning
        {
            get
            {
                return this.ytreAvgrensningField;
            }
            set
            {
                this.ytreAvgrensningField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Geometri", Namespace="http://rep.geointegrasjon.no/Felles/Geometri/xml.schema/2012.01.31")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(rep.geointegrasjon.no.Felles.Geometri.xml.schema._2012._01._31.Kurve))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(rep.geointegrasjon.no.Felles.Geometri.xml.schema._2012._01._31.Flate))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(rep.geointegrasjon.no.Felles.Geometri.xml.schema._2012._01._31.Bbox))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(rep.geointegrasjon.no.Felles.Geometri.xml.schema._2012._01._31.Punkt))]
    public partial class Geometri : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private rep.geointegrasjon.no.Felles.Geometri.xml.schema._2012._01._31.KoordinatsystemKode koordinatsystemField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false)]
        public rep.geointegrasjon.no.Felles.Geometri.xml.schema._2012._01._31.KoordinatsystemKode koordinatsystem
        {
            get
            {
                return this.koordinatsystemField;
            }
            set
            {
                this.koordinatsystemField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Kurve", Namespace="http://rep.geointegrasjon.no/Felles/Geometri/xml.schema/2012.01.31")]
    public partial class Kurve : rep.geointegrasjon.no.Felles.Geometri.xml.schema._2012._01._31.Geometri
    {
        
        private rep.geointegrasjon.no.Felles.Geometri.xml.schema._2012._01._31.KoordinatListe linjeField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public rep.geointegrasjon.no.Felles.Geometri.xml.schema._2012._01._31.KoordinatListe linje
        {
            get
            {
                return this.linjeField;
            }
            set
            {
                this.linjeField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Bbox", Namespace="http://rep.geointegrasjon.no/Felles/Geometri/xml.schema/2012.01.31")]
    public partial class Bbox : rep.geointegrasjon.no.Felles.Geometri.xml.schema._2012._01._31.Geometri
    {
        
        private rep.geointegrasjon.no.Felles.Geometri.xml.schema._2012._01._31.Koordinat nedreVenstreField;
        
        private rep.geointegrasjon.no.Felles.Geometri.xml.schema._2012._01._31.Koordinat oevreHoeyreField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false)]
        public rep.geointegrasjon.no.Felles.Geometri.xml.schema._2012._01._31.Koordinat nedreVenstre
        {
            get
            {
                return this.nedreVenstreField;
            }
            set
            {
                this.nedreVenstreField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false)]
        public rep.geointegrasjon.no.Felles.Geometri.xml.schema._2012._01._31.Koordinat oevreHoeyre
        {
            get
            {
                return this.oevreHoeyreField;
            }
            set
            {
                this.oevreHoeyreField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Koordinat", Namespace="http://rep.geointegrasjon.no/Felles/Geometri/xml.schema/2012.01.31")]
    public partial class Koordinat : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private double xField;
        
        private double yField;
        
        private double zField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public double x
        {
            get
            {
                return this.xField;
            }
            set
            {
                this.xField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public double y
        {
            get
            {
                return this.yField;
            }
            set
            {
                this.yField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double z
        {
            get
            {
                return this.zField;
            }
            set
            {
                this.zField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="KoordinatListe", Namespace="http://rep.geointegrasjon.no/Felles/Geometri/xml.schema/2012.01.31", ItemName="liste")]
    public class KoordinatListe : System.Collections.Generic.List<rep.geointegrasjon.no.Felles.Geometri.xml.schema._2012._01._31.Koordinat>
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Ring", Namespace="http://rep.geointegrasjon.no/Felles/Geometri/xml.schema/2012.01.31")]
    public partial class Ring : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private rep.geointegrasjon.no.Felles.Geometri.xml.schema._2012._01._31.KoordinatListe lukketKurveField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public rep.geointegrasjon.no.Felles.Geometri.xml.schema._2012._01._31.KoordinatListe lukketKurve
        {
            get
            {
                return this.lukketKurveField;
            }
            set
            {
                this.lukketKurveField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="RingListe", Namespace="http://rep.geointegrasjon.no/Felles/Geometri/xml.schema/2012.01.31", ItemName="liste")]
    public class RingListe : System.Collections.Generic.List<rep.geointegrasjon.no.Felles.Geometri.xml.schema._2012._01._31.Ring>
    {
    }
}
namespace rep.geointegrasjon.no.Felles.Kodeliste.xml.schema._2012._01._31
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Kode", Namespace="http://rep.geointegrasjon.no/Felles/Kodeliste/xml.schema/2012.01.31")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(rep.geointegrasjon.no.Felles.Kontakt.xml.schema._2012._01._31.PersonidentifikatorType))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(rep.geointegrasjon.no.Sak.Faser.xml.schema._2012._01._31.FaseStatus))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(rep.geointegrasjon.no.Sak.Faser.xml.schema._2012._01._31.FaseType))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(rep.geointegrasjon.no.Arkiv.Dokument.xml.schema._2012._01._31.Variantformat))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(rep.geointegrasjon.no.Arkiv.Dokument.xml.schema._2012._01._31.Format))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(rep.geointegrasjon.no.Arkiv.Dokument.xml.schema._2012._01._31.TilknyttetRegistreringSom))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(rep.geointegrasjon.no.Arkiv.Dokument.xml.schema._2012._01._31.Dokumentstatus))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(rep.geointegrasjon.no.Arkiv.Dokument.xml.schema._2012._01._31.Dokumenttype))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(rep.geointegrasjon.no.Plan.Utvidet.xml.schema._2012._01._31.PlandokumentType))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(rep.geointegrasjon.no.Plan.Utvidet.xml.schema._2012._01._31.PlanbehandlingTypeKode))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(rep.geointegrasjon.no.Plan.Utvidet.xml.schema._2012._01._31.Lovreferanse))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(rep.geointegrasjon.no.Plan.Utvidet.xml.schema._2012._01._31.WMS_PlanLayers))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(rep.geointegrasjon.no.Plan.Utvidet.xml.schema._2012._01._31.Planbestemmelse))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(rep.geointegrasjon.no.Plan.Utvidet.xml.schema._2012._01._31.PlanforholdsTypeKode))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(rep.geointegrasjon.no.Plan.Utvidet.xml.schema._2012._01._31.DispensasjonsTypeKode))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(rep.geointegrasjon.no.Plan.Utvidet.xml.schema._2012._01._31.Utnyttingstype))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(rep.geointegrasjon.no.Plan.Utvidet.xml.schema._2012._01._31.VertikalnivaaKode))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(rep.geointegrasjon.no.Plan.Utvidet.xml.schema._2012._01._31.AktoerRollekode))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(rep.geointegrasjon.no.Plan.Utvidet.xml.schema._2012._01._31.PlanEndringTypeKode))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(rep.geointegrasjon.no.Felles.Adresse.xml.schema._2012._01._31.Landkode))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(rep.geointegrasjon.no.Felles.Adresse.xml.schema._2012._01._31.EnkelAdressetype))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(rep.geointegrasjon.no.Arkiv.Kjerne.xml.schema._2012._01._31.Arkivdel))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(rep.geointegrasjon.no.Arkiv.Kjerne.xml.schema._2012._01._31.SkjermingsHjemmel))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(rep.geointegrasjon.no.Arkiv.Kjerne.xml.schema._2012._01._31.Tilgangsrestriksjon))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(rep.geointegrasjon.no.Arkiv.Kjerne.xml.schema._2012._01._31.SkjermingOpphorerAksjon))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(rep.geointegrasjon.no.Arkiv.Kjerne.xml.schema._2012._01._31.SakspartRolle))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(rep.geointegrasjon.no.Arkiv.Kjerne.xml.schema._2012._01._31.Dokumentmedium))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(rep.geointegrasjon.no.Arkiv.Kjerne.xml.schema._2012._01._31.Mappetype))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(rep.geointegrasjon.no.Arkiv.Kjerne.xml.schema._2012._01._31.Journalenhet))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(rep.geointegrasjon.no.Arkiv.Kjerne.xml.schema._2012._01._31.Korrespondanseparttype))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(rep.geointegrasjon.no.Arkiv.Kjerne.xml.schema._2012._01._31.Avskrivningsmaate))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(rep.geointegrasjon.no.Arkiv.Kjerne.xml.schema._2012._01._31.Kassasjonsvedtak))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(rep.geointegrasjon.no.Arkiv.Kjerne.xml.schema._2012._01._31.Informasjonstype))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(rep.geointegrasjon.no.Arkiv.Kjerne.xml.schema._2012._01._31.Klassifikasjonssystem))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(rep.geointegrasjon.no.Arkiv.Kjerne.xml.schema._2012._01._31.Saksstatus))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(rep.geointegrasjon.no.Arkiv.Kjerne.xml.schema._2012._01._31.Journalstatus))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(rep.geointegrasjon.no.Arkiv.Kjerne.xml.schema._2012._01._31.Forsendelsesmaate))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(rep.geointegrasjon.no.Arkiv.Kjerne.xml.schema._2012._01._31.Journalposttype))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(rep.geointegrasjon.no.Matrikkel.Basis.xml.schema._2012._01._31.BygningsendringsKode))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(rep.geointegrasjon.no.Matrikkel.Basis.xml.schema._2012._01._31.ArealmerknadKode))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(rep.geointegrasjon.no.Matrikkel.Basis.xml.schema._2012._01._31.KommuneKode))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(rep.geointegrasjon.no.Matrikkel.Basis.xml.schema._2012._01._31.NaeringsgruppeKode))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(rep.geointegrasjon.no.Matrikkel.Basis.xml.schema._2012._01._31.EiendomstypeKode))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(rep.geointegrasjon.no.Matrikkel.Basis.xml.schema._2012._01._31.BygningstypeKode))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(rep.geointegrasjon.no.Matrikkel.Basis.xml.schema._2012._01._31.EierforholdKode))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(rep.geointegrasjon.no.Matrikkel.Basis.xml.schema._2012._01._31.BygningsstatusKode))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(rep.geointegrasjon.no.Plan.Basis.xml.schema._2012._01._31.Plantype))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(rep.geointegrasjon.no.Plan.Basis.xml.schema._2012._01._31.Planstatus))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(rep.geointegrasjon.no.Matrikkel.Utvidet.xml.schema._2012._01._31.MediumKode))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(rep.geointegrasjon.no.Matrikkel.Utvidet.xml.schema._2012._01._31.EtasjeplanKode))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(rep.geointegrasjon.no.Matrikkel.Utvidet.xml.schema._2012._01._31.AnleggstypeKode))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(rep.geointegrasjon.no.Matrikkel.Utvidet.xml.schema._2012._01._31.BruksenhetstypeKode))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(rep.geointegrasjon.no.Felles.Geometri.xml.schema._2012._01._31.KoordinatsystemKode))]
    public partial class Kode : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string kodeverdiField;
        
        private string kodebeskrivelseField;
        
        private bool erGyldigField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false)]
        public string kodeverdi
        {
            get
            {
                return this.kodeverdiField;
            }
            set
            {
                this.kodeverdiField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string kodebeskrivelse
        {
            get
            {
                return this.kodebeskrivelseField;
            }
            set
            {
                this.kodebeskrivelseField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public bool erGyldig
        {
            get
            {
                return this.erGyldigField;
            }
            set
            {
                this.erGyldigField = value;
            }
        }
    }
}
namespace rep.geointegrasjon.no.Felles.Kontakt.xml.schema._2012._01._31
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PersonidentifikatorType", Namespace="http://rep.geointegrasjon.no/Felles/Kontakt/xml.schema/2012.01.31")]
    public partial class PersonidentifikatorType : rep.geointegrasjon.no.Felles.Kodeliste.xml.schema._2012._01._31.Kode
    {
    }
}
namespace rep.geointegrasjon.no.Sak.Faser.xml.schema._2012._01._31
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FaseStatus", Namespace="http://rep.geointegrasjon.no/Sak/Faser/xml.schema/2012.01.31")]
    public partial class FaseStatus : rep.geointegrasjon.no.Felles.Kodeliste.xml.schema._2012._01._31.Kode
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FaseType", Namespace="http://rep.geointegrasjon.no/Sak/Faser/xml.schema/2012.01.31")]
    public partial class FaseType : rep.geointegrasjon.no.Felles.Kodeliste.xml.schema._2012._01._31.Kode
    {
    }
}
namespace rep.geointegrasjon.no.Arkiv.Dokument.xml.schema._2012._01._31
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Variantformat", Namespace="http://rep.geointegrasjon.no/Arkiv/Dokument/xml.schema/2012.01.31")]
    public partial class Variantformat : rep.geointegrasjon.no.Felles.Kodeliste.xml.schema._2012._01._31.Kode
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Format", Namespace="http://rep.geointegrasjon.no/Arkiv/Dokument/xml.schema/2012.01.31")]
    public partial class Format : rep.geointegrasjon.no.Felles.Kodeliste.xml.schema._2012._01._31.Kode
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TilknyttetRegistreringSom", Namespace="http://rep.geointegrasjon.no/Arkiv/Dokument/xml.schema/2012.01.31")]
    public partial class TilknyttetRegistreringSom : rep.geointegrasjon.no.Felles.Kodeliste.xml.schema._2012._01._31.Kode
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Dokumentstatus", Namespace="http://rep.geointegrasjon.no/Arkiv/Dokument/xml.schema/2012.01.31")]
    public partial class Dokumentstatus : rep.geointegrasjon.no.Felles.Kodeliste.xml.schema._2012._01._31.Kode
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Dokumenttype", Namespace="http://rep.geointegrasjon.no/Arkiv/Dokument/xml.schema/2012.01.31")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(rep.geointegrasjon.no.Plan.Utvidet.xml.schema._2012._01._31.PlandokumentType))]
    public partial class Dokumenttype : rep.geointegrasjon.no.Felles.Kodeliste.xml.schema._2012._01._31.Kode
    {
    }
}
namespace rep.geointegrasjon.no.Plan.Utvidet.xml.schema._2012._01._31
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PlandokumentType", Namespace="http://rep.geointegrasjon.no/Plan/Utvidet/xml.schema/2012.01.31")]
    public partial class PlandokumentType : rep.geointegrasjon.no.Arkiv.Dokument.xml.schema._2012._01._31.Dokumenttype
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PlanbehandlingTypeKode", Namespace="http://rep.geointegrasjon.no/Plan/Utvidet/xml.schema/2012.01.31")]
    public partial class PlanbehandlingTypeKode : rep.geointegrasjon.no.Felles.Kodeliste.xml.schema._2012._01._31.Kode
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Lovreferanse", Namespace="http://rep.geointegrasjon.no/Plan/Utvidet/xml.schema/2012.01.31")]
    public partial class Lovreferanse : rep.geointegrasjon.no.Felles.Kodeliste.xml.schema._2012._01._31.Kode
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="WMS_PlanLayers", Namespace="http://rep.geointegrasjon.no/Plan/Utvidet/xml.schema/2012.01.31")]
    public partial class WMS_PlanLayers : rep.geointegrasjon.no.Felles.Kodeliste.xml.schema._2012._01._31.Kode
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Planbestemmelse", Namespace="http://rep.geointegrasjon.no/Plan/Utvidet/xml.schema/2012.01.31")]
    public partial class Planbestemmelse : rep.geointegrasjon.no.Felles.Kodeliste.xml.schema._2012._01._31.Kode
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PlanforholdsTypeKode", Namespace="http://rep.geointegrasjon.no/Plan/Utvidet/xml.schema/2012.01.31")]
    public partial class PlanforholdsTypeKode : rep.geointegrasjon.no.Felles.Kodeliste.xml.schema._2012._01._31.Kode
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DispensasjonsTypeKode", Namespace="http://rep.geointegrasjon.no/Plan/Utvidet/xml.schema/2012.01.31")]
    public partial class DispensasjonsTypeKode : rep.geointegrasjon.no.Felles.Kodeliste.xml.schema._2012._01._31.Kode
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Utnyttingstype", Namespace="http://rep.geointegrasjon.no/Plan/Utvidet/xml.schema/2012.01.31")]
    public partial class Utnyttingstype : rep.geointegrasjon.no.Felles.Kodeliste.xml.schema._2012._01._31.Kode
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="VertikalnivaaKode", Namespace="http://rep.geointegrasjon.no/Plan/Utvidet/xml.schema/2012.01.31")]
    public partial class VertikalnivaaKode : rep.geointegrasjon.no.Felles.Kodeliste.xml.schema._2012._01._31.Kode
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AktoerRollekode", Namespace="http://rep.geointegrasjon.no/Plan/Utvidet/xml.schema/2012.01.31")]
    public partial class AktoerRollekode : rep.geointegrasjon.no.Felles.Kodeliste.xml.schema._2012._01._31.Kode
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PlanEndringTypeKode", Namespace="http://rep.geointegrasjon.no/Plan/Utvidet/xml.schema/2012.01.31")]
    public partial class PlanEndringTypeKode : rep.geointegrasjon.no.Felles.Kodeliste.xml.schema._2012._01._31.Kode
    {
    }
}
namespace rep.geointegrasjon.no.Felles.Adresse.xml.schema._2012._01._31
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Landkode", Namespace="http://rep.geointegrasjon.no/Felles/Adresse/xml.schema/2012.01.31")]
    public partial class Landkode : rep.geointegrasjon.no.Felles.Kodeliste.xml.schema._2012._01._31.Kode
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EnkelAdressetype", Namespace="http://rep.geointegrasjon.no/Felles/Adresse/xml.schema/2012.01.31")]
    public partial class EnkelAdressetype : rep.geointegrasjon.no.Felles.Kodeliste.xml.schema._2012._01._31.Kode
    {
    }
}
namespace rep.geointegrasjon.no.Arkiv.Kjerne.xml.schema._2012._01._31
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Arkivdel", Namespace="http://rep.geointegrasjon.no/Arkiv/Kjerne/xml.schema/2012.01.31")]
    public partial class Arkivdel : rep.geointegrasjon.no.Felles.Kodeliste.xml.schema._2012._01._31.Kode
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SkjermingsHjemmel", Namespace="http://rep.geointegrasjon.no/Arkiv/Kjerne/xml.schema/2012.01.31")]
    public partial class SkjermingsHjemmel : rep.geointegrasjon.no.Felles.Kodeliste.xml.schema._2012._01._31.Kode
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Tilgangsrestriksjon", Namespace="http://rep.geointegrasjon.no/Arkiv/Kjerne/xml.schema/2012.01.31")]
    public partial class Tilgangsrestriksjon : rep.geointegrasjon.no.Felles.Kodeliste.xml.schema._2012._01._31.Kode
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SkjermingOpphorerAksjon", Namespace="http://rep.geointegrasjon.no/Arkiv/Kjerne/xml.schema/2012.01.31")]
    public partial class SkjermingOpphorerAksjon : rep.geointegrasjon.no.Felles.Kodeliste.xml.schema._2012._01._31.Kode
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SakspartRolle", Namespace="http://rep.geointegrasjon.no/Arkiv/Kjerne/xml.schema/2012.01.31")]
    public partial class SakspartRolle : rep.geointegrasjon.no.Felles.Kodeliste.xml.schema._2012._01._31.Kode
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Dokumentmedium", Namespace="http://rep.geointegrasjon.no/Arkiv/Kjerne/xml.schema/2012.01.31")]
    public partial class Dokumentmedium : rep.geointegrasjon.no.Felles.Kodeliste.xml.schema._2012._01._31.Kode
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Mappetype", Namespace="http://rep.geointegrasjon.no/Arkiv/Kjerne/xml.schema/2012.01.31")]
    public partial class Mappetype : rep.geointegrasjon.no.Felles.Kodeliste.xml.schema._2012._01._31.Kode
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Journalenhet", Namespace="http://rep.geointegrasjon.no/Arkiv/Kjerne/xml.schema/2012.01.31")]
    public partial class Journalenhet : rep.geointegrasjon.no.Felles.Kodeliste.xml.schema._2012._01._31.Kode
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Korrespondanseparttype", Namespace="http://rep.geointegrasjon.no/Arkiv/Kjerne/xml.schema/2012.01.31")]
    public partial class Korrespondanseparttype : rep.geointegrasjon.no.Felles.Kodeliste.xml.schema._2012._01._31.Kode
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Avskrivningsmaate", Namespace="http://rep.geointegrasjon.no/Arkiv/Kjerne/xml.schema/2012.01.31")]
    public partial class Avskrivningsmaate : rep.geointegrasjon.no.Felles.Kodeliste.xml.schema._2012._01._31.Kode
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Kassasjonsvedtak", Namespace="http://rep.geointegrasjon.no/Arkiv/Kjerne/xml.schema/2012.01.31")]
    public partial class Kassasjonsvedtak : rep.geointegrasjon.no.Felles.Kodeliste.xml.schema._2012._01._31.Kode
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Informasjonstype", Namespace="http://rep.geointegrasjon.no/Arkiv/Kjerne/xml.schema/2012.01.31")]
    public partial class Informasjonstype : rep.geointegrasjon.no.Felles.Kodeliste.xml.schema._2012._01._31.Kode
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Klassifikasjonssystem", Namespace="http://rep.geointegrasjon.no/Arkiv/Kjerne/xml.schema/2012.01.31")]
    public partial class Klassifikasjonssystem : rep.geointegrasjon.no.Felles.Kodeliste.xml.schema._2012._01._31.Kode
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Saksstatus", Namespace="http://rep.geointegrasjon.no/Arkiv/Kjerne/xml.schema/2012.01.31")]
    public partial class Saksstatus : rep.geointegrasjon.no.Felles.Kodeliste.xml.schema._2012._01._31.Kode
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Journalstatus", Namespace="http://rep.geointegrasjon.no/Arkiv/Kjerne/xml.schema/2012.01.31")]
    public partial class Journalstatus : rep.geointegrasjon.no.Felles.Kodeliste.xml.schema._2012._01._31.Kode
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Forsendelsesmaate", Namespace="http://rep.geointegrasjon.no/Arkiv/Kjerne/xml.schema/2012.01.31")]
    public partial class Forsendelsesmaate : rep.geointegrasjon.no.Felles.Kodeliste.xml.schema._2012._01._31.Kode
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Journalposttype", Namespace="http://rep.geointegrasjon.no/Arkiv/Kjerne/xml.schema/2012.01.31")]
    public partial class Journalposttype : rep.geointegrasjon.no.Felles.Kodeliste.xml.schema._2012._01._31.Kode
    {
    }
}
namespace rep.geointegrasjon.no.Matrikkel.Basis.xml.schema._2012._01._31
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BygningsendringsKode", Namespace="http://rep.geointegrasjon.no/Matrikkel/Basis/xml.schema/2012.01.31")]
    public partial class BygningsendringsKode : rep.geointegrasjon.no.Felles.Kodeliste.xml.schema._2012._01._31.Kode
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ArealmerknadKode", Namespace="http://rep.geointegrasjon.no/Matrikkel/Basis/xml.schema/2012.01.31")]
    public partial class ArealmerknadKode : rep.geointegrasjon.no.Felles.Kodeliste.xml.schema._2012._01._31.Kode
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="KommuneKode", Namespace="http://rep.geointegrasjon.no/Matrikkel/Basis/xml.schema/2012.01.31")]
    public partial class KommuneKode : rep.geointegrasjon.no.Felles.Kodeliste.xml.schema._2012._01._31.Kode
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="NaeringsgruppeKode", Namespace="http://rep.geointegrasjon.no/Matrikkel/Basis/xml.schema/2012.01.31")]
    public partial class NaeringsgruppeKode : rep.geointegrasjon.no.Felles.Kodeliste.xml.schema._2012._01._31.Kode
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EiendomstypeKode", Namespace="http://rep.geointegrasjon.no/Matrikkel/Basis/xml.schema/2012.01.31")]
    public partial class EiendomstypeKode : rep.geointegrasjon.no.Felles.Kodeliste.xml.schema._2012._01._31.Kode
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BygningstypeKode", Namespace="http://rep.geointegrasjon.no/Matrikkel/Basis/xml.schema/2012.01.31")]
    public partial class BygningstypeKode : rep.geointegrasjon.no.Felles.Kodeliste.xml.schema._2012._01._31.Kode
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EierforholdKode", Namespace="http://rep.geointegrasjon.no/Matrikkel/Basis/xml.schema/2012.01.31")]
    public partial class EierforholdKode : rep.geointegrasjon.no.Felles.Kodeliste.xml.schema._2012._01._31.Kode
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BygningsstatusKode", Namespace="http://rep.geointegrasjon.no/Matrikkel/Basis/xml.schema/2012.01.31")]
    public partial class BygningsstatusKode : rep.geointegrasjon.no.Felles.Kodeliste.xml.schema._2012._01._31.Kode
    {
    }
}
namespace rep.geointegrasjon.no.Plan.Basis.xml.schema._2012._01._31
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Plantype", Namespace="http://rep.geointegrasjon.no/Plan/Basis/xml.schema/2012.01.31")]
    public partial class Plantype : rep.geointegrasjon.no.Felles.Kodeliste.xml.schema._2012._01._31.Kode
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Planstatus", Namespace="http://rep.geointegrasjon.no/Plan/Basis/xml.schema/2012.01.31")]
    public partial class Planstatus : rep.geointegrasjon.no.Felles.Kodeliste.xml.schema._2012._01._31.Kode
    {
    }
}
namespace rep.geointegrasjon.no.Matrikkel.Utvidet.xml.schema._2012._01._31
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MediumKode", Namespace="http://rep.geointegrasjon.no/Matrikkel/Utvidet/xml.schema/2012.01.31")]
    public partial class MediumKode : rep.geointegrasjon.no.Felles.Kodeliste.xml.schema._2012._01._31.Kode
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EtasjeplanKode", Namespace="http://rep.geointegrasjon.no/Matrikkel/Utvidet/xml.schema/2012.01.31")]
    public partial class EtasjeplanKode : rep.geointegrasjon.no.Felles.Kodeliste.xml.schema._2012._01._31.Kode
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AnleggstypeKode", Namespace="http://rep.geointegrasjon.no/Matrikkel/Utvidet/xml.schema/2012.01.31")]
    public partial class AnleggstypeKode : rep.geointegrasjon.no.Felles.Kodeliste.xml.schema._2012._01._31.Kode
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BruksenhetstypeKode", Namespace="http://rep.geointegrasjon.no/Matrikkel/Utvidet/xml.schema/2012.01.31")]
    public partial class BruksenhetstypeKode : rep.geointegrasjon.no.Felles.Kodeliste.xml.schema._2012._01._31.Kode
    {
    }
}


[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(Namespace="http://rep.geointegrasjon.no/Matrikkel/Kart/xml.wsdl/2012.01.31", ConfigurationName="MatrikkelKartService")]
public interface MatrikkelKartService
{
    
    // CODEGEN: Generating message contract since element name matrikkelNummer from namespace http://rep.geointegrasjon.no/Matrikkel/Kart/xml.wsdl/2012.01.31 is not marked nillable
    [System.ServiceModel.OperationContractAttribute(Action="http://rep.geointegrasjon.no/Matrikkel/Kart/xml.wsdl/2012.01.31/#HentOmraadeForMa" +
        "trikkelenhet", ReplyAction="http://rep.geointegrasjon.no/Matrikkel/Kart/xml.wsdl/2012.01.31/MatrikkelKartServ" +
        "ice/HentOmraadeForMatrikkelenhetResponse")]
    [System.ServiceModel.FaultContractAttribute(typeof(rep.geointegrasjon.no.Felles.Teknisk.xml.schema._2012._01._31.GeointegrasjonFault), Action="http://rep.geointegrasjon.no/Matrikkel/Kart/xml.wsdl/2012.01.31/MatrikkelKartServ" +
        "ice/HentOmraadeForMatrikkelenhet/Fault/ApplicationException", Name="ApplicationFault", Namespace="http://rep.geointegrasjon.no/Felles/Teknisk/xml.schema/2012.01.31")]
    [System.ServiceModel.FaultContractAttribute(typeof(rep.geointegrasjon.no.Felles.Teknisk.xml.schema._2012._01._31.GeointegrasjonFault), Action="http://rep.geointegrasjon.no/Matrikkel/Kart/xml.wsdl/2012.01.31/MatrikkelKartServ" +
        "ice/HentOmraadeForMatrikkelenhet/Fault/FinderException", Name="FinderFault", Namespace="http://rep.geointegrasjon.no/Felles/Teknisk/xml.schema/2012.01.31")]
    [System.ServiceModel.FaultContractAttribute(typeof(rep.geointegrasjon.no.Felles.Teknisk.xml.schema._2012._01._31.GeointegrasjonFault), Action="http://rep.geointegrasjon.no/Matrikkel/Kart/xml.wsdl/2012.01.31/MatrikkelKartServ" +
        "ice/HentOmraadeForMatrikkelenhet/Fault/ImplementationException", Name="ImplementationFault", Namespace="http://rep.geointegrasjon.no/Felles/Teknisk/xml.schema/2012.01.31")]
    [System.ServiceModel.FaultContractAttribute(typeof(rep.geointegrasjon.no.Felles.Teknisk.xml.schema._2012._01._31.GeointegrasjonFault), Action="http://rep.geointegrasjon.no/Matrikkel/Kart/xml.wsdl/2012.01.31/MatrikkelKartServ" +
        "ice/HentOmraadeForMatrikkelenhet/Fault/OperationalException", Name="OperationalFault", Namespace="http://rep.geointegrasjon.no/Felles/Teknisk/xml.schema/2012.01.31")]
    [System.ServiceModel.FaultContractAttribute(typeof(rep.geointegrasjon.no.Felles.Teknisk.xml.schema._2012._01._31.GeointegrasjonFault), Action="http://rep.geointegrasjon.no/Matrikkel/Kart/xml.wsdl/2012.01.31/MatrikkelKartServ" +
        "ice/HentOmraadeForMatrikkelenhet/Fault/SystemException", Name="SystemFault", Namespace="http://rep.geointegrasjon.no/Felles/Teknisk/xml.schema/2012.01.31")]
    [System.ServiceModel.FaultContractAttribute(typeof(rep.geointegrasjon.no.Felles.Teknisk.xml.schema._2012._01._31.GeointegrasjonFault), Action="http://rep.geointegrasjon.no/Matrikkel/Kart/xml.wsdl/2012.01.31/MatrikkelKartServ" +
        "ice/HentOmraadeForMatrikkelenhet/Fault/ValidationException", Name="ValidationFault", Namespace="http://rep.geointegrasjon.no/Felles/Teknisk/xml.schema/2012.01.31")]
    HentOmraadeForMatrikkelenhetResponse HentOmraadeForMatrikkelenhet(HentOmraadeForMatrikkelenhetRequest request);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://rep.geointegrasjon.no/Matrikkel/Kart/xml.wsdl/2012.01.31/#HentOmraadeForMa" +
        "trikkelenhet", ReplyAction="http://rep.geointegrasjon.no/Matrikkel/Kart/xml.wsdl/2012.01.31/MatrikkelKartServ" +
        "ice/HentOmraadeForMatrikkelenhetResponse")]
    System.Threading.Tasks.Task<HentOmraadeForMatrikkelenhetResponse> HentOmraadeForMatrikkelenhetAsync(HentOmraadeForMatrikkelenhetRequest request);
    
    // CODEGEN: Generating message contract since element name matrikkelNummer from namespace http://rep.geointegrasjon.no/Matrikkel/Kart/xml.wsdl/2012.01.31 is not marked nillable
    [System.ServiceModel.OperationContractAttribute(Action="http://rep.geointegrasjon.no/Matrikkel/Kart/xml.wsdl/2012.01.31/#HentBboxForMatri" +
        "kkelenhet", ReplyAction="http://rep.geointegrasjon.no/Matrikkel/Kart/xml.wsdl/2012.01.31/MatrikkelKartServ" +
        "ice/HentBboxForMatrikkelenhetResponse")]
    [System.ServiceModel.FaultContractAttribute(typeof(rep.geointegrasjon.no.Felles.Teknisk.xml.schema._2012._01._31.GeointegrasjonFault), Action="http://rep.geointegrasjon.no/Matrikkel/Kart/xml.wsdl/2012.01.31/MatrikkelKartServ" +
        "ice/HentBboxForMatrikkelenhet/Fault/ApplicationException", Name="ApplicationFault", Namespace="http://rep.geointegrasjon.no/Felles/Teknisk/xml.schema/2012.01.31")]
    [System.ServiceModel.FaultContractAttribute(typeof(rep.geointegrasjon.no.Felles.Teknisk.xml.schema._2012._01._31.GeointegrasjonFault), Action="http://rep.geointegrasjon.no/Matrikkel/Kart/xml.wsdl/2012.01.31/MatrikkelKartServ" +
        "ice/HentBboxForMatrikkelenhet/Fault/FinderException", Name="FinderFault", Namespace="http://rep.geointegrasjon.no/Felles/Teknisk/xml.schema/2012.01.31")]
    [System.ServiceModel.FaultContractAttribute(typeof(rep.geointegrasjon.no.Felles.Teknisk.xml.schema._2012._01._31.GeointegrasjonFault), Action="http://rep.geointegrasjon.no/Matrikkel/Kart/xml.wsdl/2012.01.31/MatrikkelKartServ" +
        "ice/HentBboxForMatrikkelenhet/Fault/ImplementationException", Name="ImplementationFault", Namespace="http://rep.geointegrasjon.no/Felles/Teknisk/xml.schema/2012.01.31")]
    [System.ServiceModel.FaultContractAttribute(typeof(rep.geointegrasjon.no.Felles.Teknisk.xml.schema._2012._01._31.GeointegrasjonFault), Action="http://rep.geointegrasjon.no/Matrikkel/Kart/xml.wsdl/2012.01.31/MatrikkelKartServ" +
        "ice/HentBboxForMatrikkelenhet/Fault/OperationalException", Name="OperationalFault", Namespace="http://rep.geointegrasjon.no/Felles/Teknisk/xml.schema/2012.01.31")]
    [System.ServiceModel.FaultContractAttribute(typeof(rep.geointegrasjon.no.Felles.Teknisk.xml.schema._2012._01._31.GeointegrasjonFault), Action="http://rep.geointegrasjon.no/Matrikkel/Kart/xml.wsdl/2012.01.31/MatrikkelKartServ" +
        "ice/HentBboxForMatrikkelenhet/Fault/SystemException", Name="SystemFault", Namespace="http://rep.geointegrasjon.no/Felles/Teknisk/xml.schema/2012.01.31")]
    [System.ServiceModel.FaultContractAttribute(typeof(rep.geointegrasjon.no.Felles.Teknisk.xml.schema._2012._01._31.GeointegrasjonFault), Action="http://rep.geointegrasjon.no/Matrikkel/Kart/xml.wsdl/2012.01.31/MatrikkelKartServ" +
        "ice/HentBboxForMatrikkelenhet/Fault/ValidationException", Name="ValidationFault", Namespace="http://rep.geointegrasjon.no/Felles/Teknisk/xml.schema/2012.01.31")]
    HentBboxForMatrikkelenhetResponse HentBboxForMatrikkelenhet(HentBboxForMatrikkelenhetRequest request);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://rep.geointegrasjon.no/Matrikkel/Kart/xml.wsdl/2012.01.31/#HentBboxForMatri" +
        "kkelenhet", ReplyAction="http://rep.geointegrasjon.no/Matrikkel/Kart/xml.wsdl/2012.01.31/MatrikkelKartServ" +
        "ice/HentBboxForMatrikkelenhetResponse")]
    System.Threading.Tasks.Task<HentBboxForMatrikkelenhetResponse> HentBboxForMatrikkelenhetAsync(HentBboxForMatrikkelenhetRequest request);
    
    // CODEGEN: Generating message contract since element name selectionPolygon from namespace http://rep.geointegrasjon.no/Matrikkel/Kart/xml.wsdl/2012.01.31 is not marked nillable
    [System.ServiceModel.OperationContractAttribute(Action="http://rep.geointegrasjon.no/Matrikkel/Kart/xml.wsdl/2012.01.31/#FinnMatrikkelenh" +
        "eterForOmraade", ReplyAction="http://rep.geointegrasjon.no/Matrikkel/Kart/xml.wsdl/2012.01.31/MatrikkelKartServ" +
        "ice/FinnMatrikkelenheterForOmraadeResponse")]
    [System.ServiceModel.FaultContractAttribute(typeof(rep.geointegrasjon.no.Felles.Teknisk.xml.schema._2012._01._31.GeointegrasjonFault), Action="http://rep.geointegrasjon.no/Matrikkel/Kart/xml.wsdl/2012.01.31/MatrikkelKartServ" +
        "ice/FinnMatrikkelenheterForOmraade/Fault/ApplicationException", Name="ApplicationFault", Namespace="http://rep.geointegrasjon.no/Felles/Teknisk/xml.schema/2012.01.31")]
    [System.ServiceModel.FaultContractAttribute(typeof(rep.geointegrasjon.no.Felles.Teknisk.xml.schema._2012._01._31.GeointegrasjonFault), Action="http://rep.geointegrasjon.no/Matrikkel/Kart/xml.wsdl/2012.01.31/MatrikkelKartServ" +
        "ice/FinnMatrikkelenheterForOmraade/Fault/FinderException", Name="FinderFault", Namespace="http://rep.geointegrasjon.no/Felles/Teknisk/xml.schema/2012.01.31")]
    [System.ServiceModel.FaultContractAttribute(typeof(rep.geointegrasjon.no.Felles.Teknisk.xml.schema._2012._01._31.GeointegrasjonFault), Action="http://rep.geointegrasjon.no/Matrikkel/Kart/xml.wsdl/2012.01.31/MatrikkelKartServ" +
        "ice/FinnMatrikkelenheterForOmraade/Fault/ImplementationException", Name="ImplementationFault", Namespace="http://rep.geointegrasjon.no/Felles/Teknisk/xml.schema/2012.01.31")]
    [System.ServiceModel.FaultContractAttribute(typeof(rep.geointegrasjon.no.Felles.Teknisk.xml.schema._2012._01._31.GeointegrasjonFault), Action="http://rep.geointegrasjon.no/Matrikkel/Kart/xml.wsdl/2012.01.31/MatrikkelKartServ" +
        "ice/FinnMatrikkelenheterForOmraade/Fault/OperationalException", Name="OperationalFault", Namespace="http://rep.geointegrasjon.no/Felles/Teknisk/xml.schema/2012.01.31")]
    [System.ServiceModel.FaultContractAttribute(typeof(rep.geointegrasjon.no.Felles.Teknisk.xml.schema._2012._01._31.GeointegrasjonFault), Action="http://rep.geointegrasjon.no/Matrikkel/Kart/xml.wsdl/2012.01.31/MatrikkelKartServ" +
        "ice/FinnMatrikkelenheterForOmraade/Fault/SystemException", Name="SystemFault", Namespace="http://rep.geointegrasjon.no/Felles/Teknisk/xml.schema/2012.01.31")]
    [System.ServiceModel.FaultContractAttribute(typeof(rep.geointegrasjon.no.Felles.Teknisk.xml.schema._2012._01._31.GeointegrasjonFault), Action="http://rep.geointegrasjon.no/Matrikkel/Kart/xml.wsdl/2012.01.31/MatrikkelKartServ" +
        "ice/FinnMatrikkelenheterForOmraade/Fault/ValidationException", Name="ValidationFault", Namespace="http://rep.geointegrasjon.no/Felles/Teknisk/xml.schema/2012.01.31")]
    FinnMatrikkelenheterForOmraadeResponse FinnMatrikkelenheterForOmraade(FinnMatrikkelenheterForOmraadeRequest request);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://rep.geointegrasjon.no/Matrikkel/Kart/xml.wsdl/2012.01.31/#FinnMatrikkelenh" +
        "eterForOmraade", ReplyAction="http://rep.geointegrasjon.no/Matrikkel/Kart/xml.wsdl/2012.01.31/MatrikkelKartServ" +
        "ice/FinnMatrikkelenheterForOmraadeResponse")]
    System.Threading.Tasks.Task<FinnMatrikkelenheterForOmraadeResponse> FinnMatrikkelenheterForOmraadeAsync(FinnMatrikkelenheterForOmraadeRequest request);
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
public partial class HentOmraadeForMatrikkelenhetRequest
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Name="HentOmraadeForMatrikkelenhet", Namespace="http://rep.geointegrasjon.no/Matrikkel/Kart/xml.wsdl/2012.01.31", Order=0)]
    public HentOmraadeForMatrikkelenhetRequestBody Body;
    
    public HentOmraadeForMatrikkelenhetRequest()
    {
    }
    
    public HentOmraadeForMatrikkelenhetRequest(HentOmraadeForMatrikkelenhetRequestBody Body)
    {
        this.Body = Body;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.Runtime.Serialization.DataContractAttribute(Namespace="http://rep.geointegrasjon.no/Matrikkel/Kart/xml.wsdl/2012.01.31")]
public partial class HentOmraadeForMatrikkelenhetRequestBody
{
    
    [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
    public rep.geointegrasjon.no.Matrikkel.Felles.xml.schema._2012._01._31.Matrikkelnummer matrikkelNummer;
    
    [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
    public rep.geointegrasjon.no.Felles.Teknisk.xml.schema._2012._01._31.MatrikkelKontekst matrikkelKontekst;
    
    public HentOmraadeForMatrikkelenhetRequestBody()
    {
    }
    
    public HentOmraadeForMatrikkelenhetRequestBody(rep.geointegrasjon.no.Matrikkel.Felles.xml.schema._2012._01._31.Matrikkelnummer matrikkelNummer, rep.geointegrasjon.no.Felles.Teknisk.xml.schema._2012._01._31.MatrikkelKontekst matrikkelKontekst)
    {
        this.matrikkelNummer = matrikkelNummer;
        this.matrikkelKontekst = matrikkelKontekst;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
public partial class HentOmraadeForMatrikkelenhetResponse
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Name="HentOmraadeForMatrikkelenhetResponse", Namespace="http://rep.geointegrasjon.no/Matrikkel/Kart/xml.wsdl/2012.01.31", Order=0)]
    public HentOmraadeForMatrikkelenhetResponseBody Body;
    
    public HentOmraadeForMatrikkelenhetResponse()
    {
    }
    
    public HentOmraadeForMatrikkelenhetResponse(HentOmraadeForMatrikkelenhetResponseBody Body)
    {
        this.Body = Body;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.Runtime.Serialization.DataContractAttribute(Namespace="http://rep.geointegrasjon.no/Matrikkel/Kart/xml.wsdl/2012.01.31")]
public partial class HentOmraadeForMatrikkelenhetResponseBody
{
    
    [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
    public rep.geointegrasjon.no.Felles.Geometri.xml.schema._2012._01._31.OmraadeListe @return;
    
    public HentOmraadeForMatrikkelenhetResponseBody()
    {
    }
    
    public HentOmraadeForMatrikkelenhetResponseBody(rep.geointegrasjon.no.Felles.Geometri.xml.schema._2012._01._31.OmraadeListe @return)
    {
        this.@return = @return;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
public partial class HentBboxForMatrikkelenhetRequest
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Name="HentBboxForMatrikkelenhet", Namespace="http://rep.geointegrasjon.no/Matrikkel/Kart/xml.wsdl/2012.01.31", Order=0)]
    public HentBboxForMatrikkelenhetRequestBody Body;
    
    public HentBboxForMatrikkelenhetRequest()
    {
    }
    
    public HentBboxForMatrikkelenhetRequest(HentBboxForMatrikkelenhetRequestBody Body)
    {
        this.Body = Body;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.Runtime.Serialization.DataContractAttribute(Namespace="http://rep.geointegrasjon.no/Matrikkel/Kart/xml.wsdl/2012.01.31")]
public partial class HentBboxForMatrikkelenhetRequestBody
{
    
    [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
    public rep.geointegrasjon.no.Matrikkel.Felles.xml.schema._2012._01._31.Matrikkelnummer matrikkelNummer;
    
    [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
    public rep.geointegrasjon.no.Felles.Teknisk.xml.schema._2012._01._31.MatrikkelKontekst matrikkelKontekst;
    
    public HentBboxForMatrikkelenhetRequestBody()
    {
    }
    
    public HentBboxForMatrikkelenhetRequestBody(rep.geointegrasjon.no.Matrikkel.Felles.xml.schema._2012._01._31.Matrikkelnummer matrikkelNummer, rep.geointegrasjon.no.Felles.Teknisk.xml.schema._2012._01._31.MatrikkelKontekst matrikkelKontekst)
    {
        this.matrikkelNummer = matrikkelNummer;
        this.matrikkelKontekst = matrikkelKontekst;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
public partial class HentBboxForMatrikkelenhetResponse
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Name="HentBboxForMatrikkelenhetResponse", Namespace="http://rep.geointegrasjon.no/Matrikkel/Kart/xml.wsdl/2012.01.31", Order=0)]
    public HentBboxForMatrikkelenhetResponseBody Body;
    
    public HentBboxForMatrikkelenhetResponse()
    {
    }
    
    public HentBboxForMatrikkelenhetResponse(HentBboxForMatrikkelenhetResponseBody Body)
    {
        this.Body = Body;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.Runtime.Serialization.DataContractAttribute(Namespace="http://rep.geointegrasjon.no/Matrikkel/Kart/xml.wsdl/2012.01.31")]
public partial class HentBboxForMatrikkelenhetResponseBody
{
    
    [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
    public rep.geointegrasjon.no.Felles.Geometri.xml.schema._2012._01._31.Bbox @return;
    
    public HentBboxForMatrikkelenhetResponseBody()
    {
    }
    
    public HentBboxForMatrikkelenhetResponseBody(rep.geointegrasjon.no.Felles.Geometri.xml.schema._2012._01._31.Bbox @return)
    {
        this.@return = @return;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
public partial class FinnMatrikkelenheterForOmraadeRequest
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Name="FinnMatrikkelenheterForOmraade", Namespace="http://rep.geointegrasjon.no/Matrikkel/Kart/xml.wsdl/2012.01.31", Order=0)]
    public FinnMatrikkelenheterForOmraadeRequestBody Body;
    
    public FinnMatrikkelenheterForOmraadeRequest()
    {
    }
    
    public FinnMatrikkelenheterForOmraadeRequest(FinnMatrikkelenheterForOmraadeRequestBody Body)
    {
        this.Body = Body;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.Runtime.Serialization.DataContractAttribute(Namespace="http://rep.geointegrasjon.no/Matrikkel/Kart/xml.wsdl/2012.01.31")]
public partial class FinnMatrikkelenheterForOmraadeRequestBody
{
    
    [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
    public rep.geointegrasjon.no.Felles.Geometri.xml.schema._2012._01._31.Kurve selectionPolygon;
    
    [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
    public rep.geointegrasjon.no.Felles.Teknisk.xml.schema._2012._01._31.MatrikkelKontekst matrikkelKontekst;
    
    public FinnMatrikkelenheterForOmraadeRequestBody()
    {
    }
    
    public FinnMatrikkelenheterForOmraadeRequestBody(rep.geointegrasjon.no.Felles.Geometri.xml.schema._2012._01._31.Kurve selectionPolygon, rep.geointegrasjon.no.Felles.Teknisk.xml.schema._2012._01._31.MatrikkelKontekst matrikkelKontekst)
    {
        this.selectionPolygon = selectionPolygon;
        this.matrikkelKontekst = matrikkelKontekst;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
public partial class FinnMatrikkelenheterForOmraadeResponse
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Name="FinnMatrikkelenheterForOmraadeResponse", Namespace="http://rep.geointegrasjon.no/Matrikkel/Kart/xml.wsdl/2012.01.31", Order=0)]
    public FinnMatrikkelenheterForOmraadeResponseBody Body;
    
    public FinnMatrikkelenheterForOmraadeResponse()
    {
    }
    
    public FinnMatrikkelenheterForOmraadeResponse(FinnMatrikkelenheterForOmraadeResponseBody Body)
    {
        this.Body = Body;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.Runtime.Serialization.DataContractAttribute(Namespace="http://rep.geointegrasjon.no/Matrikkel/Kart/xml.wsdl/2012.01.31")]
public partial class FinnMatrikkelenheterForOmraadeResponseBody
{
    
    [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
    public rep.geointegrasjon.no.Matrikkel.Felles.xml.schema._2012._01._31.MatrikkelnummerListe @return;
    
    public FinnMatrikkelenheterForOmraadeResponseBody()
    {
    }
    
    public FinnMatrikkelenheterForOmraadeResponseBody(rep.geointegrasjon.no.Matrikkel.Felles.xml.schema._2012._01._31.MatrikkelnummerListe @return)
    {
        this.@return = @return;
    }
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface MatrikkelKartServiceChannel : MatrikkelKartService, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class MatrikkelKartServiceClient : System.ServiceModel.ClientBase<MatrikkelKartService>, MatrikkelKartService
{
    
    public MatrikkelKartServiceClient()
    {
    }
    
    public MatrikkelKartServiceClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public MatrikkelKartServiceClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public MatrikkelKartServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public MatrikkelKartServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    HentOmraadeForMatrikkelenhetResponse MatrikkelKartService.HentOmraadeForMatrikkelenhet(HentOmraadeForMatrikkelenhetRequest request)
    {
        return base.Channel.HentOmraadeForMatrikkelenhet(request);
    }
    
    public rep.geointegrasjon.no.Felles.Geometri.xml.schema._2012._01._31.OmraadeListe HentOmraadeForMatrikkelenhet(rep.geointegrasjon.no.Matrikkel.Felles.xml.schema._2012._01._31.Matrikkelnummer matrikkelNummer, rep.geointegrasjon.no.Felles.Teknisk.xml.schema._2012._01._31.MatrikkelKontekst matrikkelKontekst)
    {
        HentOmraadeForMatrikkelenhetRequest inValue = new HentOmraadeForMatrikkelenhetRequest();
        inValue.Body = new HentOmraadeForMatrikkelenhetRequestBody();
        inValue.Body.matrikkelNummer = matrikkelNummer;
        inValue.Body.matrikkelKontekst = matrikkelKontekst;
        HentOmraadeForMatrikkelenhetResponse retVal = ((MatrikkelKartService)(this)).HentOmraadeForMatrikkelenhet(inValue);
        return retVal.Body.@return;
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    System.Threading.Tasks.Task<HentOmraadeForMatrikkelenhetResponse> MatrikkelKartService.HentOmraadeForMatrikkelenhetAsync(HentOmraadeForMatrikkelenhetRequest request)
    {
        return base.Channel.HentOmraadeForMatrikkelenhetAsync(request);
    }
    
    public System.Threading.Tasks.Task<HentOmraadeForMatrikkelenhetResponse> HentOmraadeForMatrikkelenhetAsync(rep.geointegrasjon.no.Matrikkel.Felles.xml.schema._2012._01._31.Matrikkelnummer matrikkelNummer, rep.geointegrasjon.no.Felles.Teknisk.xml.schema._2012._01._31.MatrikkelKontekst matrikkelKontekst)
    {
        HentOmraadeForMatrikkelenhetRequest inValue = new HentOmraadeForMatrikkelenhetRequest();
        inValue.Body = new HentOmraadeForMatrikkelenhetRequestBody();
        inValue.Body.matrikkelNummer = matrikkelNummer;
        inValue.Body.matrikkelKontekst = matrikkelKontekst;
        return ((MatrikkelKartService)(this)).HentOmraadeForMatrikkelenhetAsync(inValue);
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    HentBboxForMatrikkelenhetResponse MatrikkelKartService.HentBboxForMatrikkelenhet(HentBboxForMatrikkelenhetRequest request)
    {
        return base.Channel.HentBboxForMatrikkelenhet(request);
    }
    
    public rep.geointegrasjon.no.Felles.Geometri.xml.schema._2012._01._31.Bbox HentBboxForMatrikkelenhet(rep.geointegrasjon.no.Matrikkel.Felles.xml.schema._2012._01._31.Matrikkelnummer matrikkelNummer, rep.geointegrasjon.no.Felles.Teknisk.xml.schema._2012._01._31.MatrikkelKontekst matrikkelKontekst)
    {
        HentBboxForMatrikkelenhetRequest inValue = new HentBboxForMatrikkelenhetRequest();
        inValue.Body = new HentBboxForMatrikkelenhetRequestBody();
        inValue.Body.matrikkelNummer = matrikkelNummer;
        inValue.Body.matrikkelKontekst = matrikkelKontekst;
        HentBboxForMatrikkelenhetResponse retVal = ((MatrikkelKartService)(this)).HentBboxForMatrikkelenhet(inValue);
        return retVal.Body.@return;
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    System.Threading.Tasks.Task<HentBboxForMatrikkelenhetResponse> MatrikkelKartService.HentBboxForMatrikkelenhetAsync(HentBboxForMatrikkelenhetRequest request)
    {
        return base.Channel.HentBboxForMatrikkelenhetAsync(request);
    }
    
    public System.Threading.Tasks.Task<HentBboxForMatrikkelenhetResponse> HentBboxForMatrikkelenhetAsync(rep.geointegrasjon.no.Matrikkel.Felles.xml.schema._2012._01._31.Matrikkelnummer matrikkelNummer, rep.geointegrasjon.no.Felles.Teknisk.xml.schema._2012._01._31.MatrikkelKontekst matrikkelKontekst)
    {
        HentBboxForMatrikkelenhetRequest inValue = new HentBboxForMatrikkelenhetRequest();
        inValue.Body = new HentBboxForMatrikkelenhetRequestBody();
        inValue.Body.matrikkelNummer = matrikkelNummer;
        inValue.Body.matrikkelKontekst = matrikkelKontekst;
        return ((MatrikkelKartService)(this)).HentBboxForMatrikkelenhetAsync(inValue);
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    FinnMatrikkelenheterForOmraadeResponse MatrikkelKartService.FinnMatrikkelenheterForOmraade(FinnMatrikkelenheterForOmraadeRequest request)
    {
        return base.Channel.FinnMatrikkelenheterForOmraade(request);
    }
    
    public rep.geointegrasjon.no.Matrikkel.Felles.xml.schema._2012._01._31.MatrikkelnummerListe FinnMatrikkelenheterForOmraade(rep.geointegrasjon.no.Felles.Geometri.xml.schema._2012._01._31.Kurve selectionPolygon, rep.geointegrasjon.no.Felles.Teknisk.xml.schema._2012._01._31.MatrikkelKontekst matrikkelKontekst)
    {
        FinnMatrikkelenheterForOmraadeRequest inValue = new FinnMatrikkelenheterForOmraadeRequest();
        inValue.Body = new FinnMatrikkelenheterForOmraadeRequestBody();
        inValue.Body.selectionPolygon = selectionPolygon;
        inValue.Body.matrikkelKontekst = matrikkelKontekst;
        FinnMatrikkelenheterForOmraadeResponse retVal = ((MatrikkelKartService)(this)).FinnMatrikkelenheterForOmraade(inValue);
        return retVal.Body.@return;
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    System.Threading.Tasks.Task<FinnMatrikkelenheterForOmraadeResponse> MatrikkelKartService.FinnMatrikkelenheterForOmraadeAsync(FinnMatrikkelenheterForOmraadeRequest request)
    {
        return base.Channel.FinnMatrikkelenheterForOmraadeAsync(request);
    }
    
    public System.Threading.Tasks.Task<FinnMatrikkelenheterForOmraadeResponse> FinnMatrikkelenheterForOmraadeAsync(rep.geointegrasjon.no.Felles.Geometri.xml.schema._2012._01._31.Kurve selectionPolygon, rep.geointegrasjon.no.Felles.Teknisk.xml.schema._2012._01._31.MatrikkelKontekst matrikkelKontekst)
    {
        FinnMatrikkelenheterForOmraadeRequest inValue = new FinnMatrikkelenheterForOmraadeRequest();
        inValue.Body = new FinnMatrikkelenheterForOmraadeRequestBody();
        inValue.Body.selectionPolygon = selectionPolygon;
        inValue.Body.matrikkelKontekst = matrikkelKontekst;
        return ((MatrikkelKartService)(this)).FinnMatrikkelenheterForOmraadeAsync(inValue);
    }
}
