define(["knockout", 'durandal/app'],
    function (ko, app) {
        "use strict";
        var title = "Resource",
            norwegian = {
                // system
                code: "No",
                norwegian: "Norsk",
                english: "Engelsk",
                warningServerUnavailable: "Får ikke kontakt med server!",
                warningLoadRecords: "Kunne ikke laste observasjonspunkter!",
                warningLoadRecordDetails: "Kunne ikke laste observasjonsdetaljer!",
                warningLoadArea: "Kunne ikke hente områdepolygon!",
                notImplemented: "Denne funksjonaliteten er foreløpig ikke ferdig implementert.",

                warningIllegalToken: "NB! Kunne ikke hente gyldig token for Norge Digitalt. Enkelte bakgrunnskart er defor ikke tilgjengelige.",
                warningLayerUnavailable: "Dette bakgrunnskartet er dessverre ikke tilgjengelig pga ugyldig eller manglende Norge Digitalt token.",
                hideWarning: "Skjul feilmeldingen",
                clickHideWarning: "Klikk skjuler feilmeldingen",
                yes: "Ja",
                no: "Nei",
                unknown: "Ukjent",
                about: "Om Naturtyper i Norge",
                aboutUrl: "http://www.artsdatabanken.no/Pages/229607",
                // bookmark.html
                loadingBookmarkStatus: "Laster utvalg fra bokmerke..",
                // listToolbar.html
                exportEnabledTitle: "Eksporter utvalget",
                exportDisabledTitle: "Utvalget er for stort for eksport (>",
                exportDisabledTitle2: "Del opp utvalget i flere deler.",
                exportTitle: "Eksport",
                exportExcelTitle: "Eksporter i MS Excel-format",
                exportExcelName: "MS Excel",
                exportVerbatimTitle: "Eksporter originaldata",
                exportVerbatimName: "Original",
                exportInfoUrl: "http://www.artsdatabanken.no/Pages/233436",
                exportInfoTitle: "Info om eksport",
                // listView.html
                listCountStatus: " observasjoner i utvalget",
                columnInstitution: "Institusjon",
                columnCollection: "Samling",
                categoryCollection: "Kategori",
                columnScientificName: "Vit. navn",
                columnScientificNameAuthor: "Autor",
                columnPopularName: "Norsk navn",
                columnTaxonGroup: "Artsgruppe",
                columnCollector: "Finner/Samler",
                columnCollected: "Funndato",
                columnLocality: "Lokalitet",
                columnPresicion: "Presisjon",
                columnMunicipality: "Kommune",
                columnCounty: "Fylke",
                columnCount: "Antall",
                columnBasisOfRecord: "Funntype",
                columnBehavior: "Aktivitet",
                columnIdentifiedBy: "Artsbestemt av",
                columnVerified: "Validert",
                columnDetails: "Vis detaljer",
                detailsText: "Detaljer",
                listPageStatusText1: "Side ",
                listPageStatusText2: ". Totalt ",
                listPageStatusText3: " observasjoner i ditt utvalg.",
                //pager.html
                showFirstPageTitle: "Vis første side",
                fastBackwardsTitle: "Hopp bakover",
                showPreviousPageTitle: "Vis forrige side",
                showNextPageTitle: "Vis neste side",
                fastForwardsTitle: "Hopp fremover",
                showLastPageTitle: "Vis siste side",
                showPageTitle: "Vis side ",
                // mainPanel.html
                copyLinkHelpTextWin: "Kopier denne lenken ved å markere den og trykke CTRL+C",
                closeButtonTitle: "Lukk",
                toggleLeftMenuButtonTitle: "Veksle meny",
                mainDropdownTitle: "Velg innhold i hovedvindu",
                // statistics.html
                makingStatisticsStatus: "Lager statistikk for ditt utvalg..",
                showStatisticsStatus1: "Viser statistikk for ditt utvalg på ",
                showStatisticsStatus2: "  observasjoner.",
                noStatisticsToShow: "Utvalget inneholder ingen observasjoner.",
                statInstitutionHeader: "Institusjoner",
                statSpeciesHeader: "Arter",
                statTaxonGroupHeader: "Artsgrupper",
                statOtherHeader: "Egenskaper",
                statColumnInstitution: "Institusjon",
                statColumnCount: "Antall observasjoner",
                statColumnDistinct: "Antall unike arter",
                statColumnScientificName: "Vitenskapelig navn",
                statColumnCategory: "Kategori",
                statColumnAuthor: "Autor",
                statColumnPopularName: "Norsk navn",
                statColumnCumulativeCount: "% av totalt antall observasjoner",
                statCumulativeCount: "Kumulativ telling: ",
                statShowMore: "Vis flere...",
                statShowAll: "Vis alle",
                statShowEmptyYears: "Vis også år uten observasjoner",
                statRedHeader: "Rødlistekategorier",
                statBlackHeader: "Fremmedartskategorier",
                statColumnPercent: "%",
                statColumnBasisOfRecord: "Funntype",
                statColumnBehavior: "Aktivitet",
                statColumnMonth: "Pr måned",
                statColumnTags: "Annet",
                statColumnTaxonGroups: "Artsgrupper",
                statYearHeader: "Antall per år",
                statColumnYear: "År",
                statTotalText1: "Totalt ",
                statTotalText2: " år med observasjoner",
                statTotalText3: " taksoner",
                yearChartYAxisText: "Antall",
                yearChartYAxisTitle: "Antall observasjoner",
                yearChartBarTitle1: "Observert i ",
                yearChartBarTitle2: " % av utvalg",
                //nav.js
                routeMapName: "Kart",
                routeMapTitle: "Vis utvalg i kart",
                routeListName: "Liste",
                routeListTitle: "Vis utvalg i liste",
                routeStatName: "Statistikk",
                routeStatTitle: "Vis statistikk for utvalget",
                routeImportName: "Import",
                routeImportTitle: "Import av kartlegginger og miljøvariabelkart (krever innlogging)",
                routeDetailsName: "Tilbake til",
                routeDetailsTitle: "",
                routeFactsheetName: "Faktaark",
                routeFactsheetTitle: "",
                routeBookmarkName: "Bokmerke",
                routeBookmarkTitle: "Gjenopprett side fra bokmerke",
                // treeview.js
                taxonGroups: "Artsgrupper",
                categories: "Rødliste- og fremmedartskategori",
                basisOfRecords: "Funntype",
                behaviors: "Aktivitet",
                institutions: "Institusjoner",
                months: "Måneder",
                other: "Annet",
                images: "Med/uten bilde",
                foundStatus: "Funnet/ikke funnet",
                notRecoveredStatus: "Gjenfunnet/ikke gjenfunnet",
                valid: "Valideringsstatus",
                unsureIdentification: "Sikker/usikker artsbestemmelse",
                spontanious: "Spontan/uspontan",
                conservationStatus: "Fredede/Prioriterte arter",
                popularNameMenu: "Populærnavn",
                scientificNameMenu: "Vitenskapelig navn",
                // maptoolbar.html
                zoomToCurrentLocationTooltip: "Posisjonen din",
                drawPolygonTooltip: "Tegn et omriss rundt ditt interesseområde for å bruke dette som geografisk filter",
                backgroundLayersTooltip: "Vis tilgjengelige bakgrunnslag",
                showMapLayersPlaceholder: "Vis tilgjengelige kartlag",
                shareLinkTitle: "Del lenke",
                showLegendTitle: "Vis/Velg tegnforklaring",
                changeLanguageTitle: "Endre språk",
                createBookmarkTitle: "Lag et bokmerke for gjeldende filter og utsnitt",
                openBookmarkTitle: "Gå til bokmerke",
                removeBookmarkTitle: "Fjern bokmerke",
                zoomToLocationWatermark: "Søk i Norgeskart, sted/gbn...",
                // mapOl3.js
                olAttribution: "Info om kartlagene",
                olZoomIn: "Zoom inn",
                olZoomOut: "Zoom ut",
                olFullScreenFalse: "Veksle fullskjermskart",
                olFullScreenTrue: "Veksle fullskjermskart",
                olRotateReset: "Tilbakestill rotasjon",
                // leftpanel.html
                mainUrl: "http://www.artsdatabanken.no",
                mainTitle: "Artskart Beta",
                notificationsTooltip: "Antall nye nyhetssaker siste 14 dager er ",
                tabAboutTitle: "Om",
                tabSearchTitle: "Søk",
                tabDetailsTitle: "Detaljer",
                tabSymbolsTitle: "Symboler",
                // featureinfo.html
                showExternalTaxonInfo: "Vis taksoninfo på Artsdatabankens nettside",
                noSelectionhelpText: "Ingen observasjon er valg. Gjør et valg i kartet eller i listevisningen for å se detaljer",
                showMainFeatures: "Vis utvalg",
                showAllFeatures: "Vis alt",
                showOriginalFeatures: "Original",
                removeLocationFromFilter: "Fjern lokalitet fra filteret",
                addLocationToFilter: "Vis kun valgte lokalitet",
                showPreviousObservation: "Vis forrige observasjon",
                showNextObservation: "Vis neste observasjon",
                reCategoryTitle: "Regionalt utdødd (RE), Norsk rødliste for arter",
                crCategoryTitle: "Kritisk truet (CR), Norsk rødliste for arter",
                enCategoryTitle: "Sterkt truet (EN), Norsk rødliste for arter",
                vuCategoryTitle: "Sårbar (VU), Norsk rødliste for arter",
                ntCategoryTitle: "Nær truet (NT), Norsk rødliste for arter",
                ddCategoryTitle: "Datamangel (D), Norsk rødliste for arter",
                lcCategoryTitle: "Livskraftig (LC), Norsk rødliste for arter",
                redlisted: "Rødlistet",
                threatened: "Truet",
                seCategoryTitle: "Svært høy risiko (SE), Fremmede arter i Norge",
                hiCategoryTitle: "Høy risiko (HI), Fremmede arter i Norge",
                phCategoryTitle: "Potensielt høy risiko (PH), Fremmede arter i Norge",
                loCategoryTitle: "Lav risiko (LO), Fremmede arter i Norge",
                nkCategoryTitle: "Ingen kjent risiko (NK), Fremmede arter i Norge",
                alienSpecies: "Fremmedart",
                blacklisted: "Svartelistet",
                taxonHeader: "Taksonomi",
                popularNameTitle: "Populærnavn:",
                taxonGroupTitle: "Artsgruppe:",
                scientificNameShortTitle: "Vit. navn",
                scientificNameTitle: "Vitenskapelig navn",
                scientificNameAuthorTitle: "Autor:",
                observationHeader: "Funnopplysninger",
                dateCollectedTitle: "Funndato:",
                collectorTitle: "Finner/samler:",
                yearIdentifiedTitle: "Bestemmelsesdato:",
                identifiedByTitle: "Artsbestemt av:",
                verifiedTitle: "Validert:",
                basisOfRecordTitle: "Funntype:",
                individualCountTitle: "Antall:",
                sexTitle: "Kjønn:",
                behaviorTitle: "Aktivitet:",
                okologiTitle: "Økologi:",
                habitatTitle: "Habitat:",
                substratTitle: "Substrat:",
                hasPicturesTitle: "Bilde(r):",
                rightsHolderTitle: "Rettighetshaver:",
                licenseTitle: "Lisens:",
                georeferenceHeader: "Georeferanse",
                latitudeTitle: "Breddegrad:",
                longitudeTitle: "Lengdegrad:",
                coordinatePrecisionTitle: "Koordinatpresisjon (m):",
                utmSoneTitle: "UTM-sone:",
                utmEastTitle: "UTM øst:",
                utmNorthTitle: "UTM nord:",
                mgrsFromTitle: "MGRS fra:",
                mgrsToTitle: "MGRS til:",
                coordinateSourceTitle: "Koordinatkilde:",
                elevationSourceTitle: "Høydedatakilde:",
                placeHeader: "Sted",
                countryTitle: "Land:",
                countyTitle: "Fylke:",
                municipalityTitle: "Kommune:",
                conservationAreaTitle: "Verneområde:",
                localityTitle: "Stedsnavn:",
                databaseDetailsHeader: "Databaseinformasjon",
                dateLastModifiedTitle: "Dato sist endret:",
                institutionNameTitle: "Institusjon: ",
                collectionTitle: "Samling: ",
                datasetTitle: "Prosjekt:",
                catalogNumberTitle: "Katalognummer: ",
                observationIdTitle: "Observasjons-id:",
                otherHeader: "Annet",
                occurrenceIdTitle: "OccurrenceId: ",
                minimumElevationTitle: "Minimum høyde:",
                maximumElevationTitle: "Maksimum høyde:",
                minimumDepthTitle: "Minimum dybde:",
                maximumDepthTitle: "Maksimum dybde:",
                notesTitle: "Notater:",
                collectingMethodTitle: "Metode:",
                protectedSpeciesTitle: "Skjermet funn:",
                urlTitle: "URL:",
                dynamicPropertiesTitle: "Dynamiske egenskaper:",
                feedbackObservationText: "Gi tilbakmelding på denne observasjonen",
                feedbackMailSubject1: "Angående observasjonen ",
                feedbackBody1: "Jeg kontakter dere angående denne observasjonen: ",
                feedbackBody2: "<Beskriv problemet her>",
                // treeview.html
                searchTitle: "Søk",
                searchBoundsTooltip: "Begrens utvalget ved å velge en art eller ved å definere et geografisk interesseområde",
                removeBoundsTooltip: "Fjern valgte interesseområde",
                zoomToPolygonTooltip: "Gå til valgte interesseområde",
                reducedObservationCountTooltip: "Antall observasjoner med gjeldende avgrensning",
                showHelpText: "Vis hjelpetekst",
                boundsHelpText: "Her kan du avgrense/klippe datamengden til det området du er interessert i.",
                simpleSearchTitle: "Enkelt søk",
                simpleSearchPlaceholder: "Søk på arter",
                includeSubTaxons: "Inkluder underliggende taksa",
                includeSubTaxonsTooltip: "Inkluder underliggende taksa ved søk på arter",
                taxonTreeHelpText: "Høyreklikk i treet for å bytte mellom populærnavn og vitenskapelige navn.",
                searchAreaPlaceholder: "Søk fylke, kommune, verneområde",
                speciesTreeTitle: "Artstre",
                filterTitle: "Filter",
                filterTooltip: "Tematisk avgrensning av observasjonene utifra typer og variabler",
                filterCountTooltip: "Antall observasjoner i gjeldende utvalg",
                removeFilterTooltip: "Nullstill gjeldene observasjons-filter",
                filterHelpText: "Her ser du observasjonene som finnes innenfor ditt valgte område. Du kan filtrere utvalget ved hjelp av menyen.",
                advancedTitle: "Avansert",
                advancedTooltip: "Avanserte valg",
                advancedCountTooltip: "Antall observasjoner i gjeldende utvalg",
                removeAdvancedTooltip: "Nullstill testENG gjeldene observasjons-filter",
                advancedHelpText: "Alle funn er knyttet til en samling, f.eks. har NHMs lavherbarium samlingsnavnet 'Lav'. Flere institusjoner kan bruke samme samlingsnavn. Et funn kan knyttes til et eller flere prosjekt eller 'datasett'. Funn fra et prosjekt kan knyttes til flere samlinger. Prosjektnavnet beskriver ofte formålet med kartleggingen. Ikke alle funn er knyttet til et prosjekt. Katalognummer er det interne nummeret til et funn eller belegg i en samling. Alle funn har unike nummer i en samling.",
                foundYearLabel: "Funn-år",
                foundYearTooltip: "Funn år fra-til. Bruk piltaster for finjusteringer",
                foundYearFrom: "Årstall fra ",
                foundYearTo: " til ",
                precisionLabel: "Koordinatpresisjon",
                precisionTooltip: "Koordinatpresisjon i meter fra-til. Bruk piltaster for finjusteringer",
                precisionFrom: "Koordinatpresisjon fra ",
                precisionTo: " til ",
                precisionUnit: " m",
                searchProjectPlaceholder: "Søk prosjekt",
                searchCollectionPlaceholder: "Søk samling",
                searchCatalogNumberPlaceholder: "Søk katalognummer"
            },
            english = {
                // system
                code: "En",
                norwegian: "Norwegian",
                english: "English",
                warningServerUnavailable: "Server unavailable!",
                warningLoadRecords: "Could not load records!",
                warningLoadRecordDetails: "Could not load record details!",
                warningLoadArea: "Could not load area polygon!",
                notImplemented: "This view is not yet implemented.",

                warningIllegalToken: "NB! Could not find valid token for Norge digitalt. Consequently, some maps are not available.",
                warningLayerUnavailable: "This map layer is unfortunately not available due to missing Norge digitalt token.",
                hideWarning: "Hide warning",
                clickHideWarning: "Click to hide warning",
                yes: "Yes",
                no: "No",
                unknown: "Unknown",
                about: "About Nature in Norway",
                aboutUrl: "http://www.artsdatabanken.no/Pages/229607",
                // bookmark.html
                loadingBookmarkStatus: "Loading filter from bookmark..",
                // listToolbar.html
                exportEnabledTitle: "Export selection",
                exportDisabledTitle: "Selection is too large for export (>",
                exportDisabledTitle2: "Try to divide the selection in multiple parts..",
                exportTitle: "Export",
                exportExcelTitle: "Export using MS Excel format",
                exportExcelName: "MS Excel",
                exportVerbatimTitle: "Export verbatim",
                exportVerbatimName: "Original",
                exportInfoUrl: "http://www.artsdatabanken.no/Pages/233436",
                exportInfoTitle: "Info about export",
                // listView.html
                listCountStatus: " records in selection",
                columnInstitution: "Institution",
                columnCollection: "Collection",
                categoryCollection: "Category",
                columnScientificName: "Sci. navn",
                columnScientificNameAuthor: "Author",
                columnPopularName: "Norwegian name",
                columnTaxonGroup: "Taxon group",
                columnCollector: "Collector",
                columnCollected: "Date collected",
                columnLocality: "Locality",
                columnPresicion: "Precision",
                columnMunicipality: "Municipality",
                columnCounty: "County",
                columnCount: "Count",
                columnBasisOfRecord: "Basis of record",
                columnBehavior: "Behavior",
                columnIdentifiedBy: "Identified by",
                columnVerified: "Verified",
                columnDetails: "Show details",
                detailsText: "Details",
                listPageStatusText1: "Page ",
                listPageStatusText2: ". There is a total of ",
                listPageStatusText3: " records in your selection.",
                //pager.html
                showFirstPageTitle: "Show first page",
                fastBackwardsTitle: "Fast backwards",
                showPreviousPageTitle: "Show previous page",
                showNextPageTitle: "Show next page",
                fastForwardsTitle: "Fast forwards",
                showLastPageTitle: "Show last page",
                showPageTitle: "Show page ",
                // mainPanel.html
                copyLinkHelpTextWin: "To copy the link, mark it and then press CTRL+C",
                closeButtonTitle: "Close",
                toggleLeftMenuButtonTitle: "Toggle menu",
                mainDropdownTitle: "Select content of main window",
                // statistics.html
                makingStatisticsStatus: "Generating statistics, please wait..",
                showStatisticsStatus1: "Statistics based on your selection of ",
                showStatisticsStatus2: "  records.",
                noStatisticsToShow: "Selection contains no records.",
                statInstitutionHeader: "Institutions",
                statSpeciesHeader: "Species",
                statTaxonGroupHeader: "Taxon groups",
                statOtherHeader: "Properties",
                statColumnInstitution: "Institution",
                statColumnCount: "Record count",
                statColumnDistinct: "Distinct species",
                statColumnScientificName: "Scientific name",
                statColumnCategory: "Category",
                statColumnAuthor: "Author",
                statColumnPopularName: "Norwegian name",
                statColumnCumulativeCount: "% of the total",
                statCumulativeCount: "Cumulative count: ",
                statShowMore: "Show more...",
                statShowAll: "Show all",
                statShowEmptyYears: "Show years without observations",
                statRedHeader: "Red List categories",
                statBlackHeader: "Black List categories",
                statColumnPercent: "%",
                statColumnBasisOfRecord: "Basis of record",
                statColumnBehavior: "Behavior",
                statColumnMonth: "Per month",
                statColumnTags: "Tags",
                statColumnTaxonGroups: "Taxon groups",
                statYearHeader: "Species / year",
                statColumnYear: "Year",
                statTotalText1: "A total of ",
                statTotalText2: " years",
                statTotalText3: " taxons",
                yearChartYAxisText: "Count",
                yearChartYAxisTitle: "Antall observasjoner",
                yearChartBarTitle1: "Observert i ",
                yearChartBarTitle2: " % av utvalg",
                //nav.js
                routeMapName: "Map",
                routeMapTitle: "Show selection in map",
                routeListName: "List",
                routeListTitle: "Show selection in a list view",
                routeStatName: "Statistics",
                routeStatTitle: "Show statistics based on selection",
                routeImportName: "Import",
                routeImportTitle: "Import av kartlegginger og miljøvariabelkart (krever innlogging)",
                routeDetailsName: "Back to",
                routeDetailsTitle: "",
                routeFactsheetName: "Fact sheet",
                routeFactsheetTitle: "",
                routeBookmarkName: "Bookmark",
                routeBookmarkTitle: "Restore page from a bookmark",
                // treeview.js
                taxonGroups: "Taxon groups",
                categories: "Categories",
                basisOfRecords: "Basis of record",
                behaviors: "Behaviors",
                institutions: "Institutions",
                months: "Months",
                other: "Other",
                images: "Pictures",
                foundStatus: "Found",
                notRecoveredStatus: "Not recovered",
                valid: "Verified observations",
                unsureIdentification: "Unsure identification",
                spontanious: "Spontaneous",
                conservationStatus: "Conservation",
                popularNameMenu: "Norwegian name",
                scientificNameMenu: "Scientific name",
                // maptoolbar.html
                zoomToCurrentLocationTooltip: "Zoom to current location",
                drawPolygonTooltip: "Draw a polygon to use it as a spatial filter",
                backgroundLayersTooltip: "Show available base layers",
                showMapLayersPlaceholder: "Show available map layers",
                shareLinkTitle: "Share link",
                showLegendTitle: "Show/choose legend",
                changeLanguageTitle: "Change language",
                createBookmarkTitle: "Create bookmark for current extent and filter",
                openBookmarkTitle: "Go to bookmark",
                removeBookmarkTitle: "Remove bookmark",
                zoomToLocationWatermark: "Zoom to location...",
                // mapOl3.js
                olAttribution: "Attribution",
                olZoomIn: "Zoom in",
                olZoomOut: "Zoom out",
                olFullScreenFalse: "Toggle full screen",
                olFullScreenTrue: "Toggle full screen",
                olRotateReset: "Reset rotation",
                // leftpanel.html
                mainUrl: "//www.biodiversity.no/",
                mainTitle: "Species Map Beta",
                notificationsTooltip: "Antall nye nyhetssaker siste 14 dager er ",
                tabAboutTitle: "About",
                tabSearchTitle: "Search",
                tabDetailsTitle: "Details",
                tabSymbolsTitle: "Symbols",
                // featureinfo.html
                showExternalTaxonInfo: "Show more taxon info",
                noSelectionhelpText: "Click on an observation to see details",
                showMainFeatures: "Show main",
                showAllFeatures: "Show all",
                showOriginalFeatures: "Verbatim",
                removeLocationFromFilter: "Remove location from filter",
                addLocationToFilter: "Show just this location",
                showPreviousObservation: "Show previous observation",
                showNextObservation: "Show next observation",
                reCategoryTitle: "Regionally Extinct (RE), The Norwegian Red List for Species",
                crCategoryTitle: "Critically Endangered (CR), The Norwegian Red List for Species",
                enCategoryTitle: "Endangered  (EN), The Norwegian Red List for Species",
                vuCategoryTitle: "Vulnerable (VU), The Norwegian Red List for Species",
                ntCategoryTitle: "Near Threatened (NT), The Norwegian Red List for Species",
                ddCategoryTitle: "Data Deficient (D), The Norwegian Red List for Species",
                lcCategoryTitle: "Least Concern (LC), The Norwegian Red List for Species",
                redlisted: "Redlisted",
                threatened: "Threatened",
                seCategoryTitle: "Severe impact (SE), The Norwegian Black List",
                hiCategoryTitle: "High impact (HI), The Norwegian Black List",
                phCategoryTitle: "Potentially high impact (PH), The Norwegian Black List",
                loCategoryTitle: "Low impact (LO), The Norwegian Black List",
                nkCategoryTitle: "No known impact (NK), The Norwegian Black List",
                alienSpecies: "Alien species",
                blacklisted: "Blacklisted",
                taxonHeader: "Taxon",
                popularNameTitle: "Popular name:",
                taxonGroupTitle: "Taxon group:",
                scientificNameShortTitle: "Sci. name",
                scientificNameTitle: "Scientific name",
                scientificNameAuthorTitle: "Author:",
                observationHeader: "Record",
                dateCollectedTitle: "Date collected:",
                collectorTitle: "Collector:",
                yearIdentifiedTitle: "Event date:",
                identifiedByTitle: "Identified by:",
                verifiedTitle: "Verified:",
                basisOfRecordTitle: "Basis of record:",
                individualCountTitle: "Individual count:",
                sexTitle: "Sex:",
                behaviorTitle: "Behavior:",
                okologiTitle: "Ecology:",
                habitatTitle: "Habitate:",
                substratTitle: "Substrate:",
                hasPicturesTitle: "Picture(s):",
                rightsHolderTitle: "Rightsholder:",
                licenseTitle: "License:",
                georeferenceHeader: "Georeference",
                latitudeTitle: "Latitude:",
                longitudeTitle: "Longitude:",
                coordinatePrecisionTitle: "Coordinate precision(m):",
                utmSoneTitle: "UTM-zone:",
                utmEastTitle: "UTM east:",
                utmNorthTitle: "UTM north:",
                mgrsFromTitle: "MGRS from:",
                mgrsToTitle: "MGRS to:",
                coordinateSourceTitle: "Coordinate source:",
                elevationSourceTitle: "Elevation source:",
                placeHeader: "Location",
                countryTitle: "Country:",
                countyTitle: "County:",
                municipalityTitle: "Municipality:",
                conservationAreaTitle: "Conservation area:",
                localityTitle: "Location name:",
                databaseDetailsHeader: "Database details",
                dateLastModifiedTitle: "Date last modified:",
                institutionNameTitle: "Institution:",
                collectionTitle: "Collection:",
                datasetTitle: "Dataset:",
                catalogNumberTitle: "Catalogue number:",
                observationIdTitle: "Observation id:",
                otherHeader: "Other",
                occurrenceIdTitle: "Occurrence id:",
                minimumElevationTitle: "Minimum eleveation:",
                maximumElevationTitle: "Maximum elevation:",
                minimumDepthTitle: "Minimum depth:",
                maximumDepthTitle: "Maximum depth:",
                notesTitle: "Notes:",
                collectingMethodTitle: "Collecting method:",
                protectedSpeciesTitle: "Locality data withheld:",
                urlTitle: "URL:",
                dynamicPropertiesTitle: "Dynamic properties:",
                feedbackObservationText: "Give feedback on this observation",
                feedbackMailSubject1: "Regarding the observation ",
                feedbackBody1: "Regarding the observation... ",
                feedbackBody2: "<Describe the problem here>",
                // treeview.html
                searchTitle: "Search",
                searchBoundsTooltip: "Limit the search result by adding a species or a geographic area.",
                removeBoundsTooltip: "Clear search",
                zoomToPolygonTooltip: "Zoom to selected area of interest",
                reducedObservationCountTooltip: "Number of observations within the current selection",
                showHelpText: "Show help text",
                boundsHelpText: "Limit the search result by adding species or a geographical areas",
                simpleSearchTitle: "Simple search",
                simpleSearchPlaceholder: "Search species",
                includeSubTaxons: "Include sub taxons",
                includeSubTaxonsTooltip: "Include sub taxons in search results",
                taxonTreeHelpText: "Right click in the tree to switch between showing scientific names and Norwegian names.",
                searchAreaPlaceholder: "Search county, municipality, conservation areas",
                speciesTreeTitle: "Tree view",
                filterTitle: "Filter",
                filterTooltip: "Filter selection based on observation- or species properties",
                filterCountTooltip: "Antall observasjoner i gjeldende utvalg",
                removeFilterTooltip: "Nullstill gjeldene observasjons-filter",
                filterHelpText: "Filter selection based on observation- or species properties.",
                advancedTitle: "Advanced",
                advancedTooltip: "Advanced filtering",
                advancedCountTooltip: "Number of observations in current selection",
                removeAdvancedTooltip: "Clear current advanced filter",
                advancedHelpText: "Search name of project (datasetName), collection or catalogue number.",
                foundYearLabel: "Years",
                foundYearTooltip: "From year / to year. Use arrow keys for small adjustments",
                foundYearFrom: "Years from ",
                foundYearTo: " to ",
                precisionLabel: "Coordinate precision",
                precisionTooltip: "Coordinate precision in meter from/to. Use arrow keys for small adjustments",
                precisionFrom: "Coordinate precision from ",
                precisionTo: " to ",
                precisionUnit: " m",
                searchProjectPlaceholder: "Search project",
                searchCollectionPlaceholder: "Search collection",
                searchCatalogNumberPlaceholder: "Search catalogue number"
            },
            selectedLanguage = ko.observable(norwegian),
            vm = {
                chooseEnglish: function () {
                    console.log("Change language to English");
                    selectedLanguage(english);
                    app.trigger('resource:languageChanged', selectedLanguage().Code);
                },
                chooseNorwegian: function () {
                    console.log("Change language to Norwegian");
                    selectedLanguage(norwegian);
                    app.trigger('resource:languageChanged', selectedLanguage().Code);
                },
                res: selectedLanguage
            };

        return vm;

    });
